import { defineConfig, loadEnv } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";
// https://vite.dev/config/
export default ({ mode }: { mode: string }) => {
  const env = loadEnv(mode, "..", "CLIENT_");

  return defineConfig({
    envDir: "..",
    envPrefix: "CLIENT_",
    server: {
      port: 3000,
      proxy: {
        "/api": {
          // Mặc định proxy đến server localhost:4000 nếu biến môi trường chưa đặt
          target: env.CLIENT_API_DOMAIN || "http://localhost:4000",
        },
      },
      allowedHosts: true,
      watch: {
        ignored: ["build/**"],
      },
    },
    plugins: [react()],
    build: {
      outDir: "build",
    },
    css: {
      preprocessorOptions: {
        scss: {
          // api: 'modern-compiler',
          silenceDeprecations: ['if-function'],
        },
      },
    },
    resolve: {
      dedupe: ['react', 'react-dom'],
      alias: {
        'react': 'react',
        'react-dom': 'react-dom',
        "@": path.resolve(__dirname, "src"),
      },
    },
    optimizeDeps: {
      include: ['react', 'react-dom'],
    },
    //generated by someone else
    define: {
      'global': 'globalThis',
      'process.env': {},
    },
  });
};
