export const ErrCodes = {
  internalServerErr: "INTERNAL_SERVER_ERR",
  failedToFetchRequestedData: "FAILED_TO_FETCH_REQUESTED_DATA",
  emailAlreadyExisted: "EMAIL_ALREADY_EXISTED",
  emailAlreadyInUse: "EMAIL_ALREADY_IN_USE",
  emailOrPasswordWasIncorrect: "EMAIL_OR_PASSWORD_WAS_INCORRECT",
  walletAlreadyLinked: "WALLET_ALREADY_LINKED",
  walletVerificationFailed: "WALLET_VERIFICATION_FAILED",
  walletNonceFailed: "WALLET_NONCE_FAILED",
  googleVerificationFailed: "GOOGLE_VERIFICATION_FAILED",
  generalUnknownErr: "GENERAL_UNKNOWN_ERR",
  networkErr: "NETWORK_ERR",
  validationErr: "VALIDATION_ERR",
  invalidTokenPayload: "INVALID_TOKEN_PAYLOAD",
  passwordAuthNotFound: "PASSWORD_AUTH_NOT_FOUND",
  passwordAlreadySet: "PASSWORD_ALREADY_SET",
  currentPasswordInvalid: "CURRENT_PASSWORD_INVALID",
  accountDeleteConfirmMismatch: "ACCOUNT_DELETE_CONFIRM_MISMATCH",
  accountDeleteForbidden: "ACCOUNT_DELETE_FORBIDDEN",
  hourlyChartHourlyExceeded90Days: "HOURLY_CHART_HOURLY_EXCEEDED_90_DAYS",
  dailyChartDailyExceeded365Days: "DAILY_CHART_DAILY_EXCEEDED_365_DAYS",
  notFound: "NOT_FOUND",
  unauthorized: "UNAUTHORIZED",
  rateLimitExceeded: "RATE_LIMIT_EXCEEDED",
  badGateway: "BAD_GATEWAY",
} as const;

export type ErrCode = (typeof ErrCodes)[keyof typeof ErrCodes];
