import type { WalletBehaviorProfile, WalletPersonaType } from "../types/walletBehaviorProfile";

const DEFAULT_PERSONA_SCORES: Record<WalletPersonaType, number> = {
    UNKNOWN: 0,
    LONG_TERM_HOLDER: 0,
    CASUAL_USER: 0,
    DEFI_TRADER: 0,
    MEMECOIN_TRADER: 0,
    NFT_COLLECTOR: 0,
    AIRDROP_FARMER: 0,
    BOT_LIKE_TRADER: 0,
    HIGH_RISK_SPECULATOR: 0,
    SMART_MONEY_LIKE: 0,
    WASH_TRADING_SUSPECT: 0,
};

function createDefaultPersonaScores(): Record<WalletPersonaType, number> {
    return { ...DEFAULT_PERSONA_SCORES };
}

export function DEFAULT_WALLET_BEHAVIOR_PROFILE(walletAddress: string): WalletBehaviorProfile {
    const generatedAt = new Date().toISOString();

    return {
        schemaVersion: "1.0.0",
        generatedAt,
        wallet: {
            address: walletAddress,
            label: null,
            clusterId: null,
            firstSeenAt: null,
            lastSeenAt: null,
        },
        analysisWindow: {
            mode: "FULL_HISTORY",
            transactionLimit: null,
            fromTimestamp: null,
            toTimestamp: null,
            latestSignatureAnalyzed: null,
            oldestSignatureAnalyzed: null,
            actualTransactionCount: 0,
            successfulTransactionCount: 0,
            failedTransactionCount: 0,
            includedSignatures: [],
        },
        dataQuality: {
            completenessScore: 0,
            missingPriceCount: 0,
            missingTokenMetadataCount: 0,
            unsupportedTransactionCount: 0,
            suspiciousParsingCount: 0,
            warnings: [],
        },
        activity: {
            activeDays: 0,
            averageTransactionsPerDay: 0,
            firstTransactionAt: null,
            lastTransactionAt: null,
            maxTransactionsInOneHour: 0,
            medianTimeBetweenTransactionsSeconds: null,
            burstActivityScore: 0,
            failedTransactionRatio: 0,
            activityLevel: "LOW",
        },
        portfolio: {
            totalEstimatedValueUsd: null,
            tokenCount: 0,
            nftCount: null,
            stablecoinValueUsd: null,
            stablecoinRatio: null,
            topHoldings: [],
            concentration: {
                top1HoldingRatio: null,
                top3HoldingRatio: null,
                top5HoldingRatio: null,
                concentrationRisk: "UNKNOWN",
            },
        },
        trading: {
            swapCount: 0,
            buyCount: 0,
            sellCount: 0,
            uniqueTokensTraded: 0,
            uniqueTokensBought: 0,
            uniqueTokensSold: 0,
            totalVolumeUsd: null,
            averageTradeSizeUsd: null,
            medianTradeSizeUsd: null,
            largestTradeUsd: null,
            stablecoinUsageRatio: null,
            averageHoldingPeriodHours: null,
            medianHoldingPeriodHours: null,
            shortTermTradeRatio: null,
            longTermHoldRatio: null,
            tradingStyle: "UNKNOWN",
        },
        pnl: {
            realizedPnlUsd: null,
            unrealizedPnlUsd: null,
            totalPnlUsd: null,
            closedPositionCount: 0,
            openPositionCount: 0,
            winningTradeCount: 0,
            losingTradeCount: 0,
            winRate: null,
            lossRate: null,
            averageWinUsd: null,
            averageLossUsd: null,
            bestTradeUsd: null,
            worstTradeUsd: null,
            profitFactor: null,
            pnlStatus: "UNKNOWN",
            calculationMethod: "UNKNOWN",
            limitations: [],
        },
        protocolUsage: {
            protocols: [],
            dominantProtocol: null,
            dexUsageRatio: null,
            lendingUsageRatio: null,
            nftMarketplaceUsageRatio: null,
            stakingUsageRatio: null,
        },
        risk: {
            riskScore: 0,
            trustScore: 0,
            riskLevel: "UNKNOWN",
            riskFactors: [],
            explanation: "No structured risk assessment has been generated yet.",
        },
        washTrading: {
            suspicionScore: 0,
            suspicionLevel: "UNKNOWN",
            signals: [],
            graphMetrics: undefined,
            explanation: "No structured wash trading assessment has been generated yet.",
        },
        persona: {
            primaryPersona: "UNKNOWN",
            secondaryPersonas: [],
            confidence: 0,
            personaScores: createDefaultPersonaScores(),
            reasoning: [],
            evidenceIds: [],
        },
        evidence: [],
        aiContext: {
            summaryFacts: [],
            doNotInferBeyond: [],
            recommendedTone: "NEUTRAL",
            userLevel: "BEGINNER",
            language: "en",
            maxSummaryLength: "SHORT",
        },
    };
}

export const EXAMPLE_WALLET_BEHAVIOR_PROFILE: WalletBehaviorProfile = {
    schemaVersion: "1.0.0",
    generatedAt: "2026-05-22T12:00:00.000Z",
    wallet: {
        address: "9xExampleWallet111111111111111111111111111111111",
        label: "Example DeFi Wallet",
        clusterId: "cluster-alpha",
        firstSeenAt: "2024-01-12T08:00:00.000Z",
        lastSeenAt: "2026-05-21T18:30:00.000Z",
    },
    analysisWindow: {
        mode: "DATE_RANGE",
        transactionLimit: null,
        fromTimestamp: "2026-02-01T00:00:00.000Z",
        toTimestamp: "2026-05-21T23:59:59.000Z",
        latestSignatureAnalyzed: "6xExampleSignature2222222222222222222222222222222222222222222",
        oldestSignatureAnalyzed: "5xExampleSignature1111111111111111111111111111111111111111111",
        actualTransactionCount: 842,
        successfulTransactionCount: 821,
        failedTransactionCount: 21,
        includedSignatures: [
            "5xExampleSignature1111111111111111111111111111111111111111111",
            "6xExampleSignature2222222222222222222222222222222222222222222",
        ],
    },
    dataQuality: {
        completenessScore: 92,
        missingPriceCount: 14,
        missingTokenMetadataCount: 3,
        unsupportedTransactionCount: 2,
        suspiciousParsingCount: 1,
        warnings: ["Some early swap prices were unavailable.", "A small number of transactions were skipped by the parser."],
    },
    activity: {
        activeDays: 57,
        averageTransactionsPerDay: 14.77,
        firstTransactionAt: "2024-01-12T08:01:00.000Z",
        lastTransactionAt: "2026-05-21T18:30:00.000Z",
        maxTransactionsInOneHour: 29,
        medianTimeBetweenTransactionsSeconds: 780,
        burstActivityScore: 68,
        failedTransactionRatio: 0.0249,
        activityLevel: "HIGH",
    },
    portfolio: {
        totalEstimatedValueUsd: 48250.75,
        tokenCount: 18,
        nftCount: 2,
        stablecoinValueUsd: 16320.0,
        stablecoinRatio: 0.3381,
        topHoldings: [
            {
                mint: "So11111111111111111111111111111111111111112",
                symbol: "SOL",
                name: "Solana",
                amount: 212.45,
                valueUsd: 31241.12,
                portfolioRatio: 0.6475,
            },
            {
                mint: "Es9vMFrzaCERkXQmB4gF8rG9r9Q7m6uH6Qf9u3W4xY1",
                symbol: "USDT",
                name: "Tether USD",
                amount: 10234.5,
                valueUsd: 10234.5,
                portfolioRatio: 0.2121,
            },
        ],
        concentration: {
            top1HoldingRatio: 0.6475,
            top3HoldingRatio: 0.8612,
            top5HoldingRatio: 0.9278,
            concentrationRisk: "HIGH",
        },
    },
    trading: {
        swapCount: 315,
        buyCount: 178,
        sellCount: 137,
        uniqueTokensTraded: 41,
        uniqueTokensBought: 32,
        uniqueTokensSold: 28,
        totalVolumeUsd: 286450.34,
        averageTradeSizeUsd: 908.57,
        medianTradeSizeUsd: 244.8,
        largestTradeUsd: 18450.0,
        stablecoinUsageRatio: 0.58,
        averageHoldingPeriodHours: 132.4,
        medianHoldingPeriodHours: 18.6,
        shortTermTradeRatio: 0.44,
        longTermHoldRatio: 0.22,
        tradingStyle: "ACTIVE_TRADER",
    },
    pnl: {
        realizedPnlUsd: 8450.21,
        unrealizedPnlUsd: 2140.33,
        totalPnlUsd: 10590.54,
        closedPositionCount: 124,
        openPositionCount: 17,
        winningTradeCount: 71,
        losingTradeCount: 53,
        winRate: 0.5726,
        lossRate: 0.4274,
        averageWinUsd: 326.41,
        averageLossUsd: -184.76,
        bestTradeUsd: 4821.18,
        worstTradeUsd: -1967.42,
        profitFactor: 1.84,
        pnlStatus: "PROFITABLE",
        calculationMethod: "AVERAGE_COST",
        limitations: ["PnL excludes some illiquid tokens without reliable price history."],
    },
    protocolUsage: {
        protocols: [
            {
                protocolName: "Jupiter",
                category: "DEX",
                transactionCount: 248,
                volumeUsd: 214320.11,
                usageRatio: 0.786,
            },
            {
                protocolName: "Kamino",
                category: "LENDING",
                transactionCount: 34,
                volumeUsd: 44220.0,
                usageRatio: 0.108,
            },
            {
                protocolName: "Tensor",
                category: "NFT_MARKETPLACE",
                transactionCount: 11,
                volumeUsd: 6025.5,
                usageRatio: 0.035,
            },
        ],
        dominantProtocol: "Jupiter",
        dexUsageRatio: 0.81,
        lendingUsageRatio: 0.11,
        nftMarketplaceUsageRatio: 0.03,
        stakingUsageRatio: 0.02,
    },
    risk: {
        riskScore: 41,
        trustScore: 59,
        riskLevel: "MEDIUM",
        riskFactors: [
            {
                code: "HIGH_FREQUENCY_ACTIVITY",
                severity: "MEDIUM",
                scoreImpact: 18,
                description: "Wallet shows sustained burst activity across multiple sessions.",
                evidenceIds: ["evidence-activity-bursts"],
            },
            {
                code: "HIGH_PORTFOLIO_CONCENTRATION",
                severity: "MEDIUM",
                scoreImpact: 12,
                description: "A large share of portfolio value sits in the top holding.",
                evidenceIds: ["evidence-concentration"],
            },
        ],
        explanation: "Moderate risk driven by active trading and a concentrated portfolio, partially offset by positive realized PnL.",
    },
    washTrading: {
        suspicionScore: 12,
        suspicionLevel: "LOW",
        signals: [
            {
                code: "REPEATED_SIMILAR_AMOUNTS",
                severity: "LOW",
                description: "Some trades repeated near-identical amounts, but not at a frequency that strongly suggests wash trading.",
                evidenceIds: ["evidence-repeated-amounts"],
            },
        ],
        graphMetrics: {
            uniqueCounterparties: 146,
            repeatedCounterpartyRatio: 0.08,
            circularFlowCount: 1,
            reciprocityRatio: 0.12,
            internalVolumeRatio: 0.05,
        },
        explanation: "Low wash trading suspicion. The wallet has broad external interaction and limited circular flow patterns.",
    },
    persona: {
        primaryPersona: "DEFI_TRADER",
        secondaryPersonas: ["SMART_MONEY_LIKE", "CASUAL_USER"],
        confidence: 0.84,
        personaScores: {
            UNKNOWN: 0,
            LONG_TERM_HOLDER: 0.1,
            CASUAL_USER: 0.34,
            DEFI_TRADER: 0.91,
            MEMECOIN_TRADER: 0.28,
            NFT_COLLECTOR: 0.12,
            AIRDROP_FARMER: 0.17,
            BOT_LIKE_TRADER: 0.08,
            HIGH_RISK_SPECULATOR: 0.33,
            SMART_MONEY_LIKE: 0.68,
            WASH_TRADING_SUSPECT: 0.05,
        },
        reasoning: [
            "Most volume routes through DEX protocols, especially Jupiter.",
            "Holding periods are mixed, with both short-term and longer-term positions.",
            "PnL is positive, but activity is still frequent enough to resemble an active DeFi participant.",
        ],
        evidenceIds: ["evidence-dex-volume", "evidence-positive-pnl", "evidence-holding-mix"],
    },
    evidence: [
        {
            id: "evidence-dex-volume",
            type: "PROTOCOL_USAGE",
            title: "DEX dominance",
            description: "Most trading volume flows through Jupiter, making DEX usage the dominant behavior.",
            relatedSignatures: ["5xExampleSignature1111111111111111111111111111111111111111111"],
            relatedTokenMints: ["So11111111111111111111111111111111111111112"],
            value: 0.81,
            threshold: 0.5,
            severity: "HIGH",
        },
        {
            id: "evidence-positive-pnl",
            type: "PNL_RESULT",
            title: "Net profitable trading",
            description: "Realized and unrealized PnL are both positive across the analyzed window.",
            value: 10590.54,
            threshold: 0,
            severity: "MEDIUM",
        },
        {
            id: "evidence-concentration",
            type: "TOKEN_HOLDING",
            title: "Concentrated holdings",
            description: "The top holding accounts for more than 60% of estimated portfolio value.",
            relatedTokenMints: ["So11111111111111111111111111111111111111112"],
            value: 0.6475,
            threshold: 0.6,
            severity: "MEDIUM",
        },
    ],
    aiContext: {
        summaryFacts: [
            "Wallet is an active DeFi trader with positive net PnL.",
            "Portfolio is moderately concentrated in SOL and stablecoins.",
            "Wash trading suspicion is low based on current structured signals.",
        ],
        doNotInferBeyond: [
            "Do not claim insider knowledge, motive, or off-chain identity.",
            "Do not infer that all trades are profitable beyond the analyzed window.",
        ],
        recommendedTone: "NEUTRAL",
        userLevel: "INTERMEDIATE",
        language: "en",
        maxSummaryLength: "MEDIUM",
    },
};