/* eslint-disable @typescript-eslint/no-unused-vars */
import "dayjs/locale/vi";
import { defineTranslation } from "./en";
import { getUsdToVndRate } from "./util/exchange-service";
import {
  defineDateTimeFormat,
  defineNumberFormat,
  defineTextFormat,
} from "./util/util-format";

export const langCode = "vi-VN";

export const format = {
  num: defineNumberFormat(
    langCode,
    {
      decimalResolution: {
        resolveCurrency(value: number): number {
          const abs = Math.abs(value);
          if (abs >= 100) return 0;
          if (abs >= 1) return 2;
          return 4;
        },
        resolveDecimal(value: number): number {
          const abs = Math.abs(value);
          if (abs >= 100) return 0;
          if (abs >= 1) return 2;
          return 4;
        },
        resolvePercent(value: number): number {
          return 2;
        },
      },
      currencyConfig: {
        currencyCode: () => "VND",
        currencyDisplay: () => "narrowSymbol",
      },
      readableCompactCurrency: {
        format(value: number, opts: Intl.NumberFormatOptions): string {
          const abs = Math.abs(value);
          const sign = value < 0 ? "-" : "";

          if (abs >= 1e12) {
            return `${sign}${(abs / 1e12).toLocaleString("vi-VN", opts)} nghìn tỷ đồng`;
          }
          if (abs >= 1e9) {
            return `${sign}${(abs / 1e9).toLocaleString("vi-VN", opts)} tỷ đồng`;
          }
          if (abs >= 1e6) {
            return `${sign}${(abs / 1e6).toLocaleString("vi-VN", opts)} triệu đồng`;
          }
          if (abs >= 1e3) {
            return `${sign}${(abs / 1e3).toLocaleString("vi-VN", opts)} nghìn đồng`;
          }
          return `${value.toLocaleString("vi-VN", { maximumFractionDigits: 0 })} đồng`;
        },
      },
      smallCompactThreshold: 1e-4,
    },
    getUsdToVndRate,
  ),
  datetime: defineDateTimeFormat(langCode, {
    datePattern: "DD/MM/YYYY",
    timePattern: "HH:mm",
    dateTimePattern: "D MMM YYYY HH:mm",
    utcDateTimePattern: "D MMM YYYY HH:mm [UTC]",
    relativeShortTimeConfig: {
      future: "trong %s",
      past: "%s trước",
      s: "1s",
      m: "1p",
      mm: "%dp",
      h: "1g",
      hh: "%dg",
      d: "1n",
      dd: "%dn",
      M: "1t",
      MM: "%dt",
      y: "1n",
      yy: "%dn",
    },
  }),
  text: defineTextFormat(),
};

export const translation = defineTranslation({
  misc: {
    badRequest: "Yêu cầu không hợp lệ",
  },
  // Common
  common: {
    cancel: "Hủy",
    confirm: "Xác nhận",
    submit: "Gửi",
    loading: "Đang tải...",
    error: "Lỗi",
    success: "Thành công",
    or: "hoặc",
    and: "và",
    noData: "Không có dữ liệu",
  },
  // Table & Pagination
  table: {
    itemsPerPageText: "Mục mỗi trang",
    pageRangeText: "Trang {{count}} / {{total}}",
    itemRangeText: "{{min}}-{{max}} của {{count}} mục",
    nextPage: "Trang tiếp theo",
    previousPage: "Trang trước",
    searchPlaceholder: "Tìm kiếm bảng...",
    filterLabel: "Bộ lọc: {{column}}",
    apply: "Áp dụng",
    selectAll: "Chọn tất cả",
    from: "Từ",
    to: "Đến",
  },
  // Authentication
  auth: {
    or: "Hoặc tiếp tục với",
    signIn: "Đăng nhập",
    signUp: "Đăng ký",
    signOut: "Đăng xuất",
    email: "Email",
    displayName: "Tên hiển thị",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    continueWithPassword: "Tiếp tục",
    continueWithGoogle: "Tiếp tục với Google",
    continueWithWallet: "Tiếp tục với ví điện tử",
    connectingWithWallet: "Đang kết nối ...",
    continueWithSelectedWallet: "Tiếp tục với ví {{walletName}}",
    continueWithConnectedWallet:
      "Tiếp tục với ví {{connectedWalletName}} - {{connectedWalletAddress}}",
    signUpSuggestion: "Bạn chưa có tài khoản? {{$createAccount}}",
    createAccount: "Tạo tài khoản mới",
    retypePassword: "Nhập lại mật khẩu",
    forgotPassword: "Quên mật khẩu?",
    dontHaveAccount: "Tôi chưa có tài khoản",
    wantAccount: "Muốn có tài khoản?",
    signUpWithGoogle: "Đăng ký với Google",
    signUpWithWallet: "Đăng ký với ví hiện có",
    termsAndPrivacy:
      "Bằng việc đăng ký, bạn đồng ý với {{$terms}} và {{$privacy}} của chúng tôi",
    termsPrefix: "Bằng việc đăng ký, bạn đồng ý với",
    termsOfService: "Điều khoản dịch vụ",
    privacyPolicy: "Chính sách bảo mật",
    terms: "Điều khoản dịch vụ",
    privacy: "Chính sách bảo mật",
    googleAuthFailed: "Xác thực Google thất bại. Vui lòng thử lại.",
    googleAuthCancelled: "Xác thực Google đã bị hủy.",
  },
  // Wallet
  wallet: {
    transactionCount: "Số lượng giao dịch",
    connectWallet: "Kết nối ví",
    selectWallet: "Chọn một ví",
    detected: "Đã phát hiện",
    notDetected: "Không phát hiện ví",
    installWallet: "Vui lòng cài đặt tiện ích ví Solana",
    blockchain: "Blockchain",
    connecting: "Đang kết nối...",
    connectionFailed: "Kết nối thất bại",
    retry: "Thử lại",
    popularWallets: "Ví Solana phổ biến",
    connectToSignIn: "Kết nối ví để đăng nhập",
    connectToSignUp: "Kết nối ví để đăng ký",
    web3Auth: "Xác thực Web3",
    selectBlockchain: "Chọn Blockchain",
    solana: "Solana",
    ethereum: "Ethereum",
    bitcoin: "Bitcoin",
    detectingWallets: "Đang phát hiện ví...",
    scanningWallets: "Đang quét ví {{blockchain}} đã cài đặt...",
    detectedWallets: "Ví đã phát hiện",
    otherWallets: "Ví khác",
    noWalletsDetected: "Không phát hiện ví",
    noWalletsFound: "Không tìm thấy ví {{blockchain}}",
    installWalletPrompt:
      "Vui lòng cài đặt tiện ích ví để tiếp tục. Nhấp vào ví bên dưới để truy cập trang cài đặt.",
    install: "Cài đặt →",
    termsAgreement:
      "Bằng việc kết nối ví, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật của chúng tôi.",
    detectionFailed: "Không thể phát hiện ví. Vui lòng thử lại.",
    // Wallet Overview
    shareWallet: "Chia sẻ ví này",
    compareWallet: "So sánh ví này",
    createAlert: "Tạo cảnh báo cho ví này",
    bookmarked: "Đã lưu",
    bookmarkWallet: "Lưu ví này",
    totalAssetValue: "Tổng giá trị tài sản",
    tradingVolume: "Khối lượng giao dịch",
    totalPnL: "Tổng lãi/lỗ",
    tokensTraded: "Token đã giao dịch",
    tokensHolding: "Token đang nắm giữ",
    filter24h: "Ngày",
    filter7d: "Tuần",
    filter30d: "Tháng",
    filter90d: "Quý",
    filter365d: "Năm",
    filterAll: "Tất cả",
    filterCustom: "Tùy chỉnh",
    filterCustomDateUnit: " Ngày",
    buyTransactionCount: "Số lệnh mua",
    buyVolume: "Khối lượng mua",
    sellTransactionCount: "Số lệnh bán",
    sellVolume: "Khối lượng bán",
    realizedPnL: "PnL đã chốt",
    unrealizedPnL: "PnL chưa chốt",
    change24hPercent: "Biến động 24H",
  },
  // Wallet Page
  walletPage: {
    addressNotFound: "Không tìm thấy địa chỉ",
    overview: "Tổng quan",
    holdings: "Nắm giữ",
    activityRisk: "Hoạt động / Rủi ro",
    activity: "Hoạt động",
    asset: "Tài sản",
    topExchange: "Sàn giao dịch hàng đầu",
    topCounterparties: "Đối tác hàng đầu",
    balanceHistory: "Lịch sử số dư",
    tokenBalanceHistory: "Lịch sử số dư Token",
    profitLoss: "Lãi & Lỗ",
    transfer: "Chuyển khoản",
    swap: "Hoán đổi",
    inflow: "Tiền vào",
    outflow: "Tiền ra",
    counterparties: "Đối tác",
    portfolio: "Danh mục đầu tư",
    signature: "Định danh giao dịch",
    buyer: "Người nhận",
    seller: "Người gửi",
    sender: "Người gửi",
    receiver: "Người nhận",
    currentWallet: "Ví hiện tại",
    type: "Loại",
    token: "Token",
    amount: "Số lượng",
    price: "Giá",
    total: "Tổng",
    time: "Thời gian",
    status: "Trạng thái",
    holding: "Đang nắm giữ",
    value: "Giá trị",
    change24h: "Thay đổi (24h)",
    // Token Details Demo
    tokensLastTraded: "Những token giao dịch gần nhất",
    tokensLastTradedDescription: "Token có hoạt động giao dịch gần đây",
    balance: "Số dư",
    profit: "Lợi nhuận",
    realizedProfit: "Lợi nhuận thực hiện",
    unrealizedProfit: "Lợi nhuận chưa thực hiện",
    totalBought: "Tổng mua",
    totalSold: "Tổng bán",
    netValue: "Giá trị ròng",
    transactions: "Giao dịch",
    avgBuySellPrice: "Giá mua/bán trung bình",
    graph: "Biểu đồ",
    recentTrades: "Giao dịch gần đây",
    recentTradesDescription: "Giao dịch gần đây trên token này",
    action: "Hành động",
    buy: "Mua",
    sell: "Bán",
    transaction: "Giao dịch",
    openInSolscan: "Mở trên Solscan",
    avgBuyPrice: "Giá mua TB",
    avgSellPrice: "Giá bán TB",
    averageTradingPrice: "Giá giao dịch trung bình",
    filter7d: "7 ngày",
    filter30d: "30 ngày",
    filter90d: "90 ngày",
    exchange: "Sàn giao dịch",
    pair: "Cặp giao dịch",
    tokenSold: "Token đã bán",
    tokenBought: "Token đã mua",
    totalValueUSD: "Tổng giá trị (USD)",
    feeInLamports: "Phí (lamport)",
    identity: "Định danh",
    uniqueTokensTraded: "Token duy nhất đã giao dịch",
    tokenList: "Danh sách token",
    instructions: "Instructions",
    view: "Xem",
    hide: "Ẩn",
    feePaid: "Đã trả",
    feePayer: "Người trả",
    feeReceivers: "Người nhận",
    baseFee: "Phí cơ bản",
    priorityFee: "Phí ưu tiên",
    perToken: "/token",
    account: "Tài khoản",
    totalVolume: "Tổng khối lượng",
    unknown: "Không xác định",
    unknownEntity: "Thực thể không xác định",
    identityKnown: "Đã biết",
    identityUnavailable: "Định danh không khả dụng",
    firstFunderTag: "Ví tài trợ đầu",
    firstFunderUnavailable: "Không có dữ liệu ví tài trợ đầu",
    openFirstFunderWallet: "Mở ví tài trợ đầu",
    walletAgeTag: "Tuổi ví",
    walletAgeUnitDay: "Ng",
    walletAgeUnitMonth: "Thg",
    walletAgeUnitYear: "Nm",
    manageTagsLabel: "Quản lý nhãn",
    signInManageTagsLabel: "Đăng nhập để quản lý nhãn",
    defaultWalletName: "Ví",
    exportPdfFailed: "Không thể xuất PDF. Vui lòng thử lại.",
    exportXlsxFailed: "Không thể xuất dữ liệu (.xlsx). Vui lòng thử lại.",
    exportZipFailed: "Không thể xuất biểu đồ (.zip). Vui lòng thử lại.",
    exportingData: "Đang xuất dữ liệu...",
    exportDataXlsx: "Xuất dữ liệu (.xlsx)",
    exportingCharts: "Đang xuất biểu đồ...",
    exportChartsZip: "Xuất biểu đồ (.zip images)",
    exportingReport: "Đang xuất báo cáo...",
    exportReportPdf: "Xuất báo cáo (.pdf)",
    aiAnalysis: "Phân tích AI",
    aiAnalysisLoading: "AI đang phân tích ví...",
    aiAnalysisFailed: "Không thể tải phân tích AI",
    aiAnalysisRetry: "Thử lại phân tích AI",
    aiNoData: "Không có dữ liệu phân tích AI",
    aiSummary: "Tóm tắt",
    aiStatusOk: "đủ dữ liệu",
    aiStatusInsufficientData: "thiếu dữ liệu",
    aiDataReadiness: "Mức sẵn sàng dữ liệu",
    aiDataAllAvailable: "Đã đủ dữ liệu",
    aiDataWaiting: "Đang chờ dữ liệu bắt buộc",
    aiDataSwaps: "Hoán đổi",
    aiDataPortfolio: "Danh mục",
    aiDataFirstFunder: "Nguồn tài trợ đầu",
    aiDataIdentity: "Định danh",
    aiDataIntelligence: "Phân tích",
    aiDepStatusAvailable: "có dữ liệu",
    aiDepStatusNoData: "không có dữ liệu",
    aiDepStatusFetching: "đang tải",
    aiGenerateAnalysis: "Tạo phân tích",
    aiGenerating: "Đang tạo...",
    aiLastUpdated: "Cập nhật",
    aiActivityProfile: "Hồ sơ hoạt động",
    aiArchetype: "Kiểu hành vi",
    aiActivityLevel: "Mức độ hoạt động",
    aiLastActive: "Hoạt động gần nhất",
    aiInteractionFingerprint: "Dấu vân tay tương tác",
    aiPreferredProtocols: "Giao thức ưu tiên",
    aiTransactionTiming: "Nhịp thời gian giao dịch",
    aiPreferredTradingTokens: "Token giao dịch ưu tiên",
    aiPreferredHoldingTokens: "Token nắm giữ ưu tiên",
    aiTradingVolumeRange: "Biên độ khối lượng giao dịch",
    aiFunder: "Nguồn tài trợ",
    aiFunderType: "Loại nguồn tài trợ",
    aiNotes: "Ghi chú",
    aiWalletAge: "Tuổi ví",
    aiAgeCategory: "Phân loại tuổi",
    aiFirstSeen: "Lần xuất hiện đầu",
    aiConsistencyAssessment: "Đánh giá độ nhất quán",
    aiSignals: "Tín hiệu",
    from: "Từ ví",
    to: "Đến ví",
  },
  dictionary: {
    tradingStrategy: {
      scalper: {
        name: "Lướt sóng nhanh",
        description:
          "Thực hiện nhiều giao dịch ngắn hạn và ưu tiên vòng quay vị thế nhanh.",
        benefit: {
          fastTurnover: "Xoay vòng vốn nhanh sang cơ hội mới.",
          adaptsVolatility:
            "Có thể phản ứng nhanh khi độ biến động thị trường tăng mạnh.",
        },
        risk: {
          feeHeavy: "Giao dịch dày có thể làm chi phí phí giao dịch tăng cao.",
          emotionalPressure:
            "Cần theo dõi liên tục và ra quyết định rất nhanh.",
        },
        rule: {
          minTrades30d: "Số lệnh tối thiểu trong 30 ngày",
          maxAvgHoldHours: "Số giờ nắm giữ trung bình tối đa",
        },
      },
      swing: {
        name: "Swing Trader",
        description:
          "Nắm bắt nhịp tăng/giảm theo chu kỳ vài ngày đến vài tuần và tránh nhiễu giao dịch quá mức.",
        benefit: {
          balancedPace:
            "Cân bằng giữa bắt cơ hội và giảm áp lực khớp lệnh liên tục.",
          trendCapture: "Phù hợp khi xu hướng trung hạn rõ ràng.",
        },
        risk: {
          gapExposure:
            "Khoảng trống giá qua đêm/cuối tuần có thể vượt điểm thoát dự kiến.",
          lateReversal:
            "Thoát lệnh chậm khi đảo chiều có thể bào mòn lợi nhuận.",
        },
        rule: {
          minTrades30d: "Số lệnh tối thiểu trong 30 ngày",
          minAvgHoldHours: "Số giờ nắm giữ trung bình tối thiểu",
        },
      },
      momentum: {
        name: "Bám theo động lượng",
        description:
          "Theo các điểm bứt phá mạnh với gia tốc về giá và khối lượng.",
        benefit: {
          strongTrendUpside:
            "Có thể mở rộng lợi nhuận khi xu hướng mạnh tiếp diễn.",
          quickInvalidation: "Mức vô hiệu rõ ràng giúp thoát lệnh có kỷ luật.",
        },
        risk: {
          falseBreakout: "Phá vỡ giả có thể gây chuỗi thua lỗ nhanh.",
          whipsawLosses:
            "Thị trường nhiễu có thể gây lỗ liên tục do vào/ra nhanh.",
        },
        rule: {
          minBuySellRatio: "Tỷ lệ áp lực mua/bán tối thiểu",
          minTrades30d: "Số lệnh tối thiểu trong 30 ngày",
        },
      },
      meanRevert: {
        name: "Hồi quy trung bình",
        description:
          "Tìm các nhịp đi quá xa và giao dịch theo hướng quay về vùng giá trung bình.",
        benefit: {
          definedEntries: "Điều kiện vào lệnh thường đo được và lặp lại được.",
          riskControlled: "Quản trị quy mô vị thế giúp kiểm soát rủi ro.",
        },
        risk: {
          trendAgainst: "Xu hướng mạnh có thể kéo dài lâu hơn kỳ vọng ban đầu.",
          patienceRequired: "Tín hiệu có thể thưa, cần kiên nhẫn và kỷ luật.",
        },
        rule: {
          maxTrades30d: "Số lệnh tối đa trong 30 ngày",
          minWinRate: "Tỷ lệ thắng tối thiểu",
        },
      },
      conviction: {
        name: "Nắm giữ niềm tin cao",
        description:
          "Xây vị thế tập trung và nắm giữ xuyên qua các chu kỳ thị trường rộng hơn.",
        benefit: {
          longCycleUpside: "Có thể hưởng lợi kép trong xu hướng dài hạn.",
          lowNoise: "Ít giao dịch hơn giúp giảm nhiễu ngắn hạn của thị trường.",
        },
        risk: {
          concentration: "Mức tập trung cao có thể khuếch đại drawdown.",
          slowExit: "Vị thế lớn có thể khó thoát nhanh khi cần thiết.",
        },
        rule: {
          maxTokensHeld: "Số token phân biệt nắm giữ tối đa",
          minAvgHoldDays: "Số ngày nắm giữ trung bình tối thiểu",
        },
      },
    },
    walletCategory: {
      smartMoney: {
        name: "Ví thông minh",
        description:
          "Ví có lịch sử lợi nhuận tốt và quyết định ổn định theo mức rủi ro.",
      },
      activeTrader: {
        name: "Ví giao dịch tích cực",
        description: "Ví có tần suất giao dịch cao, xoay vòng vị thế nhanh.",
      },
      whale: {
        name: "Ví cá voi",
        description:
          "Ví có quy mô vốn lớn, có thể ảnh hưởng thị trường thanh khoản mỏng.",
      },
      newWallet: {
        name: "Ví mới",
        description: "Ví mới hoạt động, dữ liệu hành vi lịch sử còn hạn chế.",
      },
      riskWallet: {
        name: "Ví rủi ro",
        description:
          "Ví có tín hiệu biến động cao, bất lợi, hoặc hành vi thiếu ổn định.",
      },
    },
    firstFunderCategory: {
      cex: {
        name: "Sàn tập trung",
        description:
          "Nguồn tiền nạp đầu tiên có dấu hiệu đến từ ví nóng của sàn tập trung.",
      },
      dexRouter: {
        name: "Router DEX",
        description:
          "Nguồn tiền nạp đầu tiên xuất phát từ hạ tầng router hoán đổi phi tập trung.",
      },
      bridge: {
        name: "Cầu nối",
        description:
          "Nguồn tiền nạp đầu tiên cho thấy hành vi chuyển tài sản liên chuỗi.",
      },
      otc: {
        name: "Bàn OTC",
        description:
          "Nguồn tiền nạp đầu tiên có khả năng từ ví thanh toán OTC.",
      },
      unknown: {
        name: "Nguồn chưa xác định",
        description:
          "Không đủ tín hiệu on-chain để phân loại nguồn tài trợ một cách tin cậy.",
      },
    },
  },
  // Market Page
  marketPage: {
    topTokens: "Các token hàng đầu",
    topTokensDescription: "Top 50 token theo vốn hóa",
    trending: "Xu hướng",
    trendingTokens: "Token đang thịnh hành",
    trendingTokensDescription: "10 token xu hướng hàng đầu",
    tokenPerformanceTitle: "Hiệu suất Token",
    profitableTraders: "Các ví đang có lời",
    profitableTradersDescription: "Top 20 trader theo vốn hóa",
    topGainers: "Top lãi nhất",
    topGainersDesc:
      "Danh sách các nhà giao dịch có lợi nhuận cao nhất trong khoảng thời gian này.",
    topLosers: "Top lỗ nhất",
    topLosersDesc:
      "Danh sách các nhà giao dịch có lợi nhuận thấp nhất (lỗ nhiều nhất) trong khoảng thời gian này.",
    recentTrades: "Giao dịch gần đây",
    recentTradesDesc:
      "Các giao dịch hoán đổi token gần nhất trên các sàn giao dịch.",
    marketHeatmapDescription: "Bản đồ nhiệt các token theo vốn hóa",
    marketCap: "Vốn hóa",
    volume24h: "Khối lượng 24h",
    change24h: "Thay đổi 24h",
    price: "Giá",
    token: "Token",
    trader: "Ví ",
    profits: "Lợi nhuận",
    volume: "Khối lượng",
    trades: "Giao dịch",
    time: "Thời gian",
    value: "Giá trị",
    amount: "Số lượng",
    transaction: "Giao dịch",
    openInSolscan: "Mở trong Solscan",
    addToWatchlist: "Thêm vào danh sách theo dõi",
    removeFromWatchlist: "Xóa khỏi danh sách theo dõi",
    marketMap: "Bản đồ thị trường",
    clearWatchlist: "Xóa danh sách",
    sortBy: "Sắp xếp theo",
    more: "xem thêm",
    watchlistEmptyTitle: "Danh sách theo dõi đang trống",
    watchlistEmptySubtitle:
      "Bắt đầu gắn sao các token ở tab 'Tất cả' để theo dõi tại đây!",
    all: "Tất cả",
    watchlist: "Danh sách theo dõi",
    allTokensTitle: "Giá tiền điện tử theo vốn hóa thị trường",
    allTokensSubtitle:
      "Thị trường tiền điện tử toàn cầu đang tiếp tục phát triển với nhiều hoạt động đáng chú ý. Dưới đây là tổng quan về các token hàng đầu theo vốn hóa thị trường và hiệu suất gần đây của chúng.",
    watchlistTitle: "Danh sách theo dõi của bạn",
    watchlistSubtitle:
      "Theo dõi các token yêu thích của bạn và giám sát hiệu suất của chúng ở một nơi duy nhất.",
    tradesTitle: "Hoạt động thị trường & Điểm nổi bật",
    tradesSubtitle:
      "Khám phá các nhà giao dịch có lợi nhuận cao nhất và các giao dịch hoán đổi mới nhất trên các sàn giao dịch phi tập trung.",
    filterAll: "Tất cả",
    filterGreaterThan: ">{{val}}",
    selectToken: "Chọn một token để xem chi tiết",
    allTimeHigh: "Cao nhất mọi thời đại (ATH)",
    allTimeLow: "Thấp nhất mọi thời đại (ATL)",
    na: "N/A",
  },
  // Wallet Comparison Page
  walletComparison: {
    selectedWallets: "Ví đã chọn",
    addWalletAddress: "Thêm địa chỉ ví",
    enterWalletAddress: "Nhập địa chỉ ví...",
    noWalletsSelected: "Chưa chọn ví nào. Thêm địa chỉ ví để so sánh.",
    general: "Tổng quan",
    holdings: "Tài sản nắm giữ",
    profitRiskManagement: "Quản lý lợi nhuận & rủi ro",
    exportPdf: "Xuất PDF",
    generatingPdf: "Đang tạo PDF...",
    pdfReportTitle: "Báo cáo so sánh ví",
    pdfGeneratedDate: "Ngày tạo",
    pdfWalletsCompared: "Số ví so sánh",
    pdfWalletAddresses: "Địa chỉ ví",
  },
  // Wallet Report PDF Template
  wallet_report: {
    wallet_audit_report: "Báo Cáo Kiểm Toán Ví",
    export_date: "Ngày xuất:",
    first_funder: "Nguồn nạp đầu tiên:",
    wallet_age: "Tuổi ví:",
    wallet_address: "ĐỊA CHỈ VÍ",
    executive_summary: "Tóm Tắt Tổng Quan",
    total_asset_value: "Tổng Giá Trị Tài Sản",
    total_pnl: "Tổng Lời/Lỗ",
    total_trading_volume: "Tổng Khối Lượng Giao Dịch",
    overview_details: "Chi Tiết Tổng Quan",
    metrics_period: "Kỳ Báo Cáo",
    period_24h: "24H",
    transaction_count: "Số Lượng Giao Dịch",
    buy_tx_count: "Số Giao Dịch Mua",
    sell_tx_count: "Số Giao Dịch Bán",
    buy_volume: "Khối Lượng Mua",
    sell_volume: "Khối Lượng Bán",
    realized_pnl: "Lời/Lỗ Đã Chốt",
    unrealized_pnl: "Lời/Lỗ Tạm Tính",
    tokens_holding: "Token Đang Giữ",
    tokens_traded: "Token Đã Giao Dịch",
    overview: "Tổng Quan",
    balance_trend: "Xu Hướng Số Dư",
    profit_loss: "Lời & Lỗ",
    daily_pnl: "Lời/Lỗ Hằng Ngày",
    cumulative_pnl: "Lời/Lỗ Lũy Kế",
    holdings: "Tài Sản Nắm Giữ",
    activity_risk: "Hoạt Động / Rủi Ro",
    asset_change_24h: "Biến Động Tài Sản (24H)",
    no_tags: "Không có nhãn",
  },
  // Navigation
  nav: {
    market: "Thị trường",
    alerts: "Cảnh báo",
    dashboard: "Bảng điều khiển",
    notification: "Thông báo",
    profile: "Hồ sơ",
    settings: "Cài đặt",
    theme: "Giao diện",
    language: "Ngôn ngữ",
    account: "Tài khoản",
    search: "Tìm kiếm",
    switchToLightTheme: "Chuyển sang Chủ đề Sáng",
    switchToDarkTheme: "Chuyển sang Chủ đề Tối",
    searchPlaceholder: "Tìm token hoặc địa chỉ ví…",
    searchHint: "Nhập để tìm token, pool hoặc ví",
    searchLoading: "Đang tìm kiếm…",
    searchNoResults: "Không tìm thấy kết quả nào",
    searchTokens: "Token",
    searchPools: "Pools",
    searchWallets: "Ví",
    searchNavigate: "để di chuyển",
    searchSelect: "để chọn",
    searchClose: "để đóng",
    searchStats: "Thống kê",
    searchRank: "Thứ hạng",
    searchMarketCap: "Vốn hóa",
    searchVolume: "Khối lượng 24h",
    searchPrice: "Giá",
    searchLast7Days: "7 ngày qua",
  },
  alertsPage: {
    title: "Cảnh báo ví",
    subtitle:
      "Theo dõi ví Solana và đẩy toàn bộ danh sách lên webhook Helius (enhanced) sau mỗi thay đổi.",
    addressLabel: "Địa chỉ ví",
    addressPlaceholder: "Địa chỉ Solana (Base58)",
    labelOptional: "Nhãn (tuỳ chọn)",
    labelPlaceholder: "vd. Theo dõi cá voi",
    followButton: "Theo dõi ví",
    loadingList: "Đang tải danh sách ví…",
    emptyList: "Chưa theo dõi ví nào.",
    tableAddress: "Địa chỉ",
    tableLabel: "Nhãn",
    tableAdded: "Thêm lúc",
    successSaved: "Đã lưu ví.",
    successHelius: "Đã đồng bộ webhook Helius với danh sách địa chỉ mới.",
    partialHelius:
      "Đã lưu ví nhưng đồng bộ Helius thất bại. Kiểm tra HELIUS_API_KEY và WEBHOOK_PUBLIC_URL trên server rồi thử lại.",
    errorInvalidAddress: "Địa chỉ Solana không hợp lệ.",
    errorDuplicate: "Địa chỉ này đã được theo dõi.",
    errorGeneric: "Có lỗi xảy ra. Vui lòng thử lại.",
    heliusOk: "Helius: OK",
    heliusFailed: "Helius: thất bại",
    tableActions: "Hành động",
    deleteSuccess: "Đã xoá ví và đồng bộ Helius.",
    deletePartial:
      "Đã xoá ví nhưng đồng bộ Helius thất bại. Địa chỉ cũ có thể vẫn nhận sự kiện cho đến lần đồng bộ kế tiếp.",
    deleteFailed: "Không thể xoá ví. Vui lòng thử lại.",
    deleteNotFound: "Ví đã được xoá trước đó.",
    signInRequired: "Vui lòng đăng nhập để quản lý danh sách ví theo dõi.",
    discordSectionTitle: "Thông báo Discord",
    discordLabel: "Discord Webhook URL",
    discordPlaceholder: "https://discord.com/api/webhooks/...",
    discordSaveButton: "Lưu",
    discordSaved: "Đã lưu Discord Webhook URL.",
    discordSaveError: "Lưu URL Discord thất bại. Vui lòng thử lại.",
    emailSectionTitle: "Thông báo qua email",
    emailToggleLabel: "Gửi cảnh báo qua email",
    emailRegisteredHint: "Email đã đăng ký: {{email}}",
    emailNoRegistered: "Chưa có email đăng ký. Nhập email thay thế bên dưới.",
    emailOverrideLabel: "Email thay thế (tuỳ chọn)",
    emailOverridePlaceholder: "Để trống để dùng email đã đăng ký",
    emailSaveButton: "Lưu",
    emailSaved: "Đã lưu cài đặt email.",
    emailSaveError: "Lưu cài đặt email thất bại. Vui lòng thử lại.",
    emailNoDestination:
      "Bật thông báo email với email đã đăng ký hoặc email thay thế.",
    ruleModalTitle: "Tạo cảnh báo mới",
    ruleModalLabel: "Cảnh báo",
    ruleStep1Indicator: "(1) Sự kiện giao dịch — (2) Gửi thông báo",
    ruleStep2Indicator: "(1) Sự kiện giao dịch — (2) Gửi thông báo",
    ruleTraderLabel: "Trader (địa chỉ ví)",
    ruleActionLabel: "Loại hành động",
    ruleActionSwap: "Swap",
    ruleActionTransfer: "Chuyển",
    ruleActionAll: "Mọi hoạt động",
    ruleVolFrom: "Khối lượng từ",
    ruleVolTo: "Khối lượng đến",
    ruleVolUnit: "Đơn vị khối lượng",
    ruleUnitUsd: "USD (server quy đổi SOL qua WEBHOOK_SOL_PRICE_USD)",
    ruleUnitSol: "SOL (on-chain)",
    ruleTriggerLegend: "Kích hoạt",
    ruleTriggerOnce: "Một lần",
    ruleTriggerAlways: "Luôn luôn",
    ruleExpiry: "Hết hạn",
    ruleUseDefault: "Dùng cài đặt Discord & email mặc định",
    ruleToggleOff: "Tắt",
    ruleToggleOn: "Bật",
    ruleDiscordOverride: "Discord webhook (ghi đè)",
    ruleEmailOverride: "Email (ghi đè)",
    ruleNameLabel: "Tên cảnh báo",
    rulePreviewLabel: "Tin nhắn (tự động)",
    ruleBack: "Quay lại",
    ruleCancel: "Huỷ",
    ruleNext: "Tiếp",
    ruleSave: "Lưu",
    ruleCreateOpen: "Tạo cảnh báo mới",
    ruleTableTitle: "Quy tắc cảnh báo nâng cao",
    ruleTableSubtitle:
      "Helius gửi luồng sự kiện một lần; máy chủ áp điều kiện của bạn trước khi Discord hoặc email.",
    ruleTableEmpty: "Chưa có quy tắc cảnh báo đang hiệu lực.",
    ruleTableName: "Tên",
    ruleTableWallet: "Ví",
    ruleTableAction: "Hành động",
    ruleTableVolume: "Khối lượng",
    ruleTableTrigger: "Kích hoạt",
    ruleTableExpires: "Hết hạn",
    ruleDeleteSuccess: "Đã xoá quy tắc và đồng bộ Helius.",
    rulePreviewBody: "Ví {{wallet}} trên Solana có {{verb}} với {{range}}.",
    rulePreviewVerbSwap: "một giao dịch swap",
    rulePreviewVerbTransfer: "một giao dịch chuyển",
    rulePreviewVerbAny: "hoạt động",
    rulePreviewRangeBoth:
      "giá trị lớn hơn {{min}}{{sym}} và nhỏ hơn {{max}}{{sym}}",
    rulePreviewRangeMin: "giá trị lớn hơn {{min}}{{sym}}",
    rulePreviewWalletPlaceholder: "(địa chỉ ví)",
    ruleErrorWallet: "Nhập địa chỉ ví Solana hợp lệ.",
    ruleErrorMinVol: "Khối lượng tối thiểu phải là số dương.",
    ruleErrorMaxVol:
      "Khối lượng tối đa để trống hoặc lớn hơn hoặc bằng tối thiểu.",
    ruleErrorExpiry: "Chọn thời điểm hết hạn trong tương lai.",
    ruleErrorDelivery:
      "Cung cấp URL Discord webhook và/hoặc email ghi đè hợp lệ.",
    ruleSaveError: "Không thể lưu quy tắc cảnh báo.",
    ruleLoading: "Đang tải quy tắc cảnh báo…",
    ruleCreateSuccess:
      "Đã lưu quy tắc cảnh báo và cập nhật danh sách địa chỉ tới Helius.",
  },
  lang: {
    vi: "Vietnam - Tiếng Việt (Vietnamese)",
    en: "Mỹ - English (English)",
  },
  // Validation errors
  validation: {
    required: "Trường này là bắt buộc",
    identifierRequired: "Tên người dùng hoặc email là bắt buộc",
    identifierInvalid:
      "Vui lòng nhập email hoặc tên người dùng hợp lệ (tối thiểu 3 ký tự)",
    emailRequired: "Email là bắt buộc",
    invalidEmail: "Vui lòng nhập địa chỉ email hợp lệ",
    usernameRequired: "Tên người dùng là bắt buộc",
    usernameTooShort: "Tên người dùng phải có ít nhất 3 ký tự",
    usernameTooLong: "Tên người dùng không được quá 20 ký tự",
    usernameInvalidChars:
      "Tên người dùng chỉ được chứa chữ cái, số và dấu gạch dưới",
    passwordRequired: "Mật khẩu là bắt buộc",
    passwordTooShort: "Mật khẩu phải có ít nhất {{min}} ký tự",
    passwordComplexity:
      "Mật khẩu phải chứa ít nhất một chữ hoa, một chữ thường và một số",
    confirmPasswordRequired: "Vui lòng xác nhận mật khẩu",
    passwordsDoNotMatch: "Mật khẩu không khớp",
    invalidCredentials: "Tên người dùng hoặc mật khẩu không hợp lệ",
    accountExists: "Tài khoản với email này đã tồn tại",
    networkError: "Lỗi mạng. Vui lòng thử lại.",
    registrationFailed: "Đăng ký thất bại. Vui lòng thử lại.",
  },
  // Showcase page
  showcase: {
    title: "Bộ sưu tập component Yoca",
    subtitle: "Xác thực & Điều hướng UI",
    signInSection: "Component đăng nhập",
    signUpSection: "Component đăng ký",
    walletSection: "Kết nối ví",
    googleAuthSection: "Xác thực Google",
    navigationSection: "Thanh điều hướng",
    placeholderContent: "Đây là nội dung mẫu để minh họa.",
  },
  // Charts
  charts: {
    // Common
    loading: "Đang tải dữ liệu biểu đồ...",
    refreshing: "Đang làm mới...",
    retry: "Thử lại",
    export: "Xuất",
    fullscreen: "Toàn màn hình",
    miniPlayer: "Trình phát nhỏ",
    exitFullscreen: "Thoát toàn màn hình",

    // Viewing modes
    enterFullscreenMode: "Vào chế độ toàn màn hình",
    openMiniPlayer: "Mở trình phát nhỏ",
    chartViewingModes: "Chế độ xem biểu đồ",
    fullscreenView: "Chế độ toàn màn hình",
    exitFullscreenEsc: "Thoát toàn màn hình (ESC)",
    closeMiniPlayer: "Đóng trình phát nhỏ",
    closeMiniPlayerEsc: "Đóng trình phát nhỏ (ESC)",
    dragToMove: "Kéo để di chuyển",
    maximize: "Phóng to",
    minimize: "Thu nhỏ",

    // Timezone
    selectTimezone: "Chọn múi giờ",
    timezone: "Múi giờ",
    timezoneOptions: "Tùy chọn múi giờ",
    searchTimezones: "Tìm kiếm múi giờ...",
    noTimezonesFound: "Không tìm thấy múi giờ",
    localTime: "Giờ địa phương",
    utc: "UTC",

    // Loading states
    loadingChartData: "Đang tải dữ liệu biểu đồ {{title}}",
    refreshingChartData: "Đang làm mới dữ liệu biểu đồ {{title}}",
    chartLoadedSuccessfully: "Biểu đồ {{title}} đã tải thành công",
    errorLoadingChart: "Lỗi khi tải biểu đồ {{title}}",
    noDataForChart: "Không có dữ liệu cho biểu đồ {{title}}",

    // Empty state
    noDataTitle: "Không có dữ liệu",
    noDataMessage: "Không có dữ liệu để hiển thị cho bộ lọc đã chọn.",
    resetFilters: "Đặt lại bộ lọc",
    adjustFilters: "Thử điều chỉnh bộ lọc hoặc khoảng thời gian",
    noWalletsTitle: "Chưa chọn ví",
    noData: "Không có dữ liệu",

    // TreeMap
    treemapNoData: "Không có dữ liệu",

    // Error state
    errorTitle: "Không thể tải biểu đồ",
    errorMessage: "Đã xảy ra lỗi khi tải dữ liệu biểu đồ.",
    technicalDetails: "Chi tiết kỹ thuật",
    networkError: "Lỗi mạng. Vui lòng kiểm tra kết nối.",
    serverError: "Lỗi máy chủ. Vui lòng thử lại sau.",

    // Export
    exportChart: "Xuất biểu đồ",
    exportFormatOptions: "Tùy chọn định dạng xuất",
    exportPNG: "Xuất dưới dạng PNG",
    exportSVG: "Xuất dưới dạng SVG",
    exportCSV: "Xuất dưới dạng CSV",
    exportPDF: "Xuất dưới dạng PDF",
    pngFormat: "PNG",
    svgFormat: "SVG",
    csvFormat: "CSV",
    pdfFormat: "PDF",
    retinaBadge: "Ảnh",
    vectorBadge: "Vector",
    dataBadge: "Dữ liệu",
    pdfBadge: "PDF",
    exportSuccess: "Xuất biểu đồ thành công",
    exportFailed: "Xuất thất bại. Vui lòng thử lại.",

    // Filters
    timePeriod: "Khoảng thời gian",
    last7Days: "7 ngày qua",
    last30Days: "30 ngày qua",
    last60Days: "60 ngày qua",
    last90Days: "90 ngày qua",
    lastYear: "Năm qua",
    allTime: "Toàn bộ thời gian",
    customRange: "Tùy chỉnh",
    tokens: "Token",
    allTokens: "Tất cả Token",
    transactionType: "Loại giao dịch",
    allTypes: "Tất cả loại",
    trades: "Giao dịch",
    transfers: "Chuyển khoản",
    deposits: "Nạp tiền",
    withdrawals: "Rút tiền",
    wallets: "Ví",

    // Chart titles
    balanceTrend: "Xu hướng số dư",
    assetDistribution: "Phân bổ tài sản",
    profitLoss: "Lãi & Lỗ",
    exchangeComparison: "So sánh sàn giao dịch",
    counterpartyActivity: "Hoạt động đối tác",
    volumeBenchmark: "Đánh giá khối lượng",
    transactionDistribution: "Phân bổ giao dịch",
    holdingDurations: "Thời gian nắm giữ",
    aggregatedAssetDistribution: "Phân bổ tài sản tổng hợp",

    // Chart specific
    balanceChart: {
      title: "Lịch sử số dư",
      totalBalance: "Tổng số dư",
      change: "Thay đổi",
      date: "Ngày",
      balance: "Số dư",
      selectTokenLabel: "Chọn token",
      selectModeTokenLabel: "Chọn chế độ/token",
      add: "Thêm",
      switch: "Chuyển đổi",
      all: "Tất cả",
      window7d: "7 Ngày",
      window30d: "30 Ngày",
      notAvailable: "K.D",
      noDataDelta: "--",
      removeTag: "Xóa nhãn",
      atLeastOneTagRequired: "Cần chọn ít nhất một nhãn",
    },
    walletSingleBalanceChart: {
      title: "Xu hướng số dư theo ví",
      notAvailable: "K.D",
      window: {
        label: "Khoảng",
        days7: "7 Ngày",
        days30: "30 Ngày",
      },
      walletTable: {
        title: "Danh sách ví",
        wallet: "Ví",
        netWorth: "Giá trị ròng",
        balanceChange24h: "Thay đổi 24h",
      },
      ariaLabels: {
        windowToggle: "Chuyển khoảng thời gian biểu đồ số dư",
      },
    },
    assetDistributionChart: {
      title: "Phân bổ tài sản",
      totalValue: "Tổng giá trị",
      asset: "Tài sản",
      value: "Giá trị",
      percentage: "Phần trăm",
      assetPrice: "Giá hiện tại",
      noWalletsMessage: "Vui lòng chọn ít nhất một ví để xem phân bổ tài sản.",
      others: "Khác",
      filters: {
        top: "Top",
        topN: "Top N",
        minPct: "Min %",
        all: "Tất cả",
        allPercent: "Tất cả %",
        top5: "Top 5",
        top10: "Top 10",
        minPct1: ">1%",
        minPct5: ">5%",
        minPct10: ">10%",
      },
      ariaLabels: {
        topNFilter: "Bộ lọc Top N",
        minPctFilter: "Bộ lọc Min %",
      },
      filtersMenu: "Bộ lọc",
      legend: {
        clickToHide: "Nhấp để ẩn {name}",
        clickToShow: "Nhấp để hiển thị {name}",
      },
      export: {
        name: "Phân bổ tài sản",
      },
    },
    aggregatedAssetDistributionChart: {
      title: "Phân bổ tài sản tổng hợp",
      totalValue: "Tổng giá trị",
      value: "Giá trị",
      percentage: "Phần trăm",
      noWalletsMessage:
        "Vui lòng chọn ít nhất một ví để xem phân bổ tài sản tổng hợp.",
      others: "Khác",
      mode: {
        label: "Chế độ",
        single: "Một ví",
        aggregate: "Nhiều ví tổng hợp",
      },
      walletTable: {
        title: "Danh sách ví",
        wallet: "Ví",
        walletName: "Tên ví",
        walletAddress: "Địa chỉ ví",
        netWorth: "Giá trị ròng",
        uniqueTokenCount: "Số token",
        isSelected: "Đã chọn",
        selectedCount: "{count} ví đã chọn",
        selection: "Lựa chọn",
        unknownWallet: "Ví không xác định",
      },
      filters: {
        top: "Top",
        topN: "Top N",
        minValue: "Min %",
        all: "Tất cả",
        allPercent: "Tất cả %",
        top5: "Top 5",
        top10: "Top 10",
        minPct1: ">1%",
        minPct5: ">5%",
        minPct10: ">10%",
      },
      ariaLabels: {
        modeToggle: "Chuyển chế độ phân bổ tài sản",
        topNFilter: "Bộ lọc Top N",
        minPctFilter: "Bộ lọc Min %",
        walletSelector: "Chọn ví {wallet}",
      },
      export: {
        name: "Phân bổ tài sản tổng hợp",
      },
    },
    pnlChart: {
      title: "Lãi & Lỗ",
      dailyPnL: "Lãi/Lỗ hàng ngày",
      cumulativePnL: "Lãi/Lỗ tích lũy",
      profit: "Lãi",
      loss: "Lỗ",
      date: "Ngày",
      totalProfit: "Tổng lãi",
      totalLoss: "Tổng lỗ",
      netPnL: "Lãi/Lỗ ròng",
      aggregation: "Tổng hợp",
      daily: "Hàng ngày",
      weekly: "Hàng tuần",
      monthly: "Hàng tháng",
      both: "Lãi/Lỗ hàng ngày + tích lũy",
    },
    exchangeComparisonChart: {
      title: "So sánh hoạt động sàn giao dịch",
      exchange: "Sàn giao dịch",
      deposits: "Nạp tiền",
      withdrawals: "Rút tiền",
      count: "Số giao dịch",
      volume: "Khối lượng",
      metric: "Chỉ số",
      transactionCount: "Số giao dịch",
      volumeUSD: "Khối lượng",
    },
    counterpartyActivityChart: {
      title: "Phân tích hoạt động đối tác",
      counterparty: "Đối tác",
      transactionCount: "Số giao dịch",
      totalVolume: "Tổng khối lượng",
      limit: "Hiển thị top",
      top10: "Top 10",
      top20: "Top 20",
      top50: "Top 50",
    },
    volumeBenchmarkChart: {
      title: "So sánh khối lượng giao dịch",
      volume: "Khối lượng",
      date: "Ngày",
      wallet: "Ví",
      chartType: "Loại biểu đồ",
      line: "Đường",
      bar: "Cột",
      showLabels: "Hiển thị nhãn",
    },
    transactionDistributionChart: {
      title: "Phân tích hoạt động giao dịch",
      transactionCounts: "Số lượng giao dịch",
      uniqueTokens: "Số loại Token được giao dịch",
      date: "Ngày",
      count: "Số lượng",
      tokens: "Token",
      chartMode: "Chế độ biểu đồ",
      stacked: "Xếp chồng",
      grouped: "Nhóm",
    },
    holdingDurationsChart: {
      title: "Thời gian nắm giữ token",
      token: "Token",
      duration: "Thời gian",
      days: "Ngày",
      weeks: "Tuần",
      months: "Tháng",
      timeUnit: "Đơn vị thời gian",
      topN: "Hiển thị top",
      wallet: "Ví",
    },
    totalTradingVolumeChart: {
      title: "Xếp hạng tổng khối lượng giao dịch",
    },
    tradingVolumePerTransactionChart: {
      title: "Khối lượng giao dịch trên mỗi giao dịch",
      volume: "Khối lượng",
    },
    tradingVolumeDistributionChart: {
      title: "Phân bổ khối lượng giao dịch",
      volume: "Khối lượng",
      percentage: "Phần trăm",
      totalVolume: "Tổng khối lượng",
      noWalletsTitle: "Chưa chọn ví",
      noWalletsMessage:
        "Vui lòng chọn ít nhất một ví để xem phân bổ khối lượng giao dịch.",
      buy: "Mua",
      sell: "Bán",
    },
    tokenPriceChart: {
      price: "Giá {{tokenSymbol}}",
      volume: "Khối lượng {{tokenSymbol}}",
      marketCap: "Vốn hóa thị trường {{tokenSymbol}}",
    },
    stablecoinRatioChart: {
      title: "Tỷ lệ Stablecoin",
    },
    rollingAnnualReturn: {
      title: "Lợi nhuận trượt hàng năm",
      rollingReturn: "Lợi nhuận lăn",
      cumulativeReturn: "Lợi nhuận tích lũy",
      month: "Tháng",
      quarter: "Quý",
      year: "Năm",
      custom: "Tùy chỉnh",
      days: "Ngày",
    },
    priceHistoryChart: {
      title: "Lịch sử giá",
    },
    marketHeatmap: {
      title: "Bản đồ nhiệt thị trường",
    },
    winrateChart: {
      title: "Phân tích tỷ lệ thắng",
    },
    drawdownChart: {
      title: "Phân tích sụt giảm",
      visibility: {
        active: "Đang hiển thị",
        hidden: "Đã ẩn",
      },
      stats: {
        maxDrawdown: "Sụt giảm tối đa",
        daysSinceMaxDD: "Số ngày kể từ sụt giảm tối đa",
        currentDrawdown: "Sụt giảm hiện tại",
        maxDDDate: "Ngày sụt giảm tối đa",
        days: "ngày",
      },
    },
    averageRollingAnnualReturn: {
      title: "Lợi nhuận hàng năm lăn trung bình",
      returnPercent: "Lợi nhuận",
      month: "Tháng",
      quarter: "Quý",
      year: "Năm",
      custom: "Tùy chỉnh",
      days: "Ngày",
    },
  },
  ERROR: {
    EMAIL_ALREADY_EXISTED: "Email đã tồn tại",
    EMAIL_OR_PASSWORD_WAS_INCORRECT: "Email hoặc mật khẩu không đúng",
    FAILED_TO_FETCH_REQUESTED_DATA: "Không thể lấy dữ liệu yêu cầu",
    GOOGLE_VERIFICATION_FAILED: "Xác thực Google thất bại. Vui lòng thử lại.",
    WALLET_ALREADY_LINKED: "Ví này đã được liên kết với một người dùng khác.",
    WALLET_VERIFICATION_FAILED: "Xác thực ví thất bại. Vui lòng thử lại.",
    WALLET_NONCE_FAILED: "Không thể khởi tạo xác thực ví. Vui lòng thử lại.",
    INTERNAL_SERVER_ERR: "Có sự cố với máy chủ. Vui lòng thử lại sau.",
    GENERAL_UNKNOWN_ERR: "Lỗi chưa xác định.",
    NETWORK_ERR: "Lỗi đường truyền. Vui lòng thử lại sau.",
    VALIDATION_ERR:
      "Dữ liệu gửi lên không hợp lệ. Vui lòng kiểm tra và thử lại.",
    INVALID_TOKEN_PAYLOAD: "Dữ liệu token không hợp lệ.",
    PASSWORD_AUTH_NOT_FOUND:
      "Tài khoản chưa cấu hình phương thức đăng nhập bằng mật khẩu.",
    PASSWORD_ALREADY_SET:
      "Tài khoản đã có phương thức đăng nhập bằng mật khẩu.",
    CURRENT_PASSWORD_INVALID: "Mật khẩu hiện tại không đúng.",
    EMAIL_ALREADY_IN_USE: "Email này đang được sử dụng bởi tài khoản khác.",
    ACCOUNT_DELETE_CONFIRM_MISMATCH:
      "Nội dung xác nhận xóa tài khoản không khớp.",
    ACCOUNT_DELETE_FORBIDDEN:
      "Yêu cầu xóa tài khoản chưa được xác thực hợp lệ.",
    HOURLY_CHART_HOURLY_EXCEEDED_90_DAYS:
      "Dữ liệu biểu đồ hàng giờ không thể vượt quá 90 ngày. Vui lòng chọn khoảng thời gian ngắn hơn.",
    DAILY_CHART_DAILY_EXCEEDED_365_DAYS:
      "Dữ liệu biểu đồ hàng ngày không thể vượt quá 365 ngày. Vui lòng chọn khoảng thời gian ngắn hơn.",
    NOT_FOUND: "Không tìm thấy",
    UNAUTHORIZED: "Không được ủy quyền",
    RATE_LIMIT_EXCEEDED: "Quá nhiều yêu cầu. Vui lòng thử lại sau.",
    BAD_GATEWAY: "Cổng trung gian không hợp lệ. Vui lòng thử lại sau.",
  },
  token: {
    overviewSectionTitle: "Tổng quan",
    historicalPriceSectionTitle: "Lịch sử giá",
    overviewChart: {
      price: "Giá",
      marketCap: "Vốn hóa thị trường",
      noData: "Không có dữ liệu biểu đồ",
      noCoingeckoId: "token có thể không có ID CoinGecko",
    },
    range24h: "Khoảng giá 24h",
    marketCap: "Vốn hóa thị trường",
    fullyDilutedValuation: "Định giá pha loãng",
    tradingVolume24h: "Lượng giao dịch 24 giờ",
    circulatingSupply: "Nguồn cung lưu hành",
    totalSupply: "Tổng cung",
    maxSupply: "Nguồn cung tối đa",
    info: "Thông tin",
    website: "Trang web",
    explorers: "Trình khám phá",
    community: "Cộng đồng",
    allTimeHigh: "Giá cao nhất mọi thời đại",
    allTimeLow: "Giá thấp nhất mọi thời đại",
    marketsTitle: "Thị trường {{name}}",
    marketsDescription:
      "Các sàn giao dịch phi tập trung hàng đầu giao dịch {{name}}.",
    topHoldersTitle: "Top 10 người nắm giữ {{name}}",
    topHoldersDescription: "Top 10 người nắm giữ token {{name}}.",
    trendingCoins: "Tiền điện tử thịnh hành",
    header: {
      copy: "Sao chép địa chỉ",
      twitter: "X (Twitter)",
      searchX: "Tìm trên X",
      discord: "Tham gia Discord",
      coingecko: "Xem trên CoinGecko",
    },
    chart: {
      loadingPool: "Đang tải biểu đồ...",
    },
    poolSelector: {
      selectPool: "Chọn Pool",
    },
    tabs: {
      overview: "Tổng quan",
      markets: "Thị trường",
      news: "Tin tức",
      trending: "Thịnh hành",
      historicalData: "Dữ liệu lịch sử",
    },
    news: {
      title: "Tin tức & Cập nhật",
      cached: "Đã lưu tạm",
      cachedTooltip: "Lấy từ lần truy vấn gần đây",
      fetch: "Lấy tin tức",
      fetchTooltip: "Lấy tin tức cho token này",
      refresh: "Làm mới tin tức",
      refreshTooltip: "Làm mới tin tức mới nhất cho token này",
      loading: "Đang tải tin tức...",
      errorPrefix: "Lỗi khi tải tin tức:",
      empty: "Không tìm thấy bài viết nào cho {{name}}.",
      tryRefresh: "Thử làm mới",
      showing: "Đang hiển thị",
      of: "trên",
      loadMore: "Tải thêm",
      expand: "Mở rộng",
      collapse: "Thu gọn",
      snippetsTitle: "Đoạn trích thêm",
      contextTitle: "Ngữ cảnh token",
      priceChartTitle: "Giá",
      marketCapChartTitle: "Vốn hóa thị trường",
      noSnippets: "Không có đoạn trích thêm.",
      noContext: "Không có dữ liệu ngữ cảnh token trong cache.",
      loadingContext: "Đang tải ngữ cảnh...",
      tokenContextLabel: "Ngữ cảnh cho {{symbol}}",
      posted: "Bài viết được đăng",
      sourceAlt: "Biểu tượng nguồn tin",
      sourceFallback: "Tin tức",
      openArticle: "Mở bài viết",
    },
    marketsTable: {
      rank: "Thứ hạng",
      exchange: "Sàn giao dịch",
      pair: "Cặp",
      price: "Giá",
      change24h: "Thay đổi",
      volume24h: "Lượng giao dịch",
      liquidity: "Thanh khoản",
      txns24h: "Số giao dịch",
    },
    marketStats: {
      priceUsd: "GIÁ",
      priceBaseQuote: "GIÁ BASE/QUOTE",
      liquidity: "THANH KHOẢN",
      marketCap: "VỐN HÓA TT",
      marketCapTip: "Vốn hóa thị trường",
      fdv: "ĐG pha loãng",
      fdvTip: "Định giá pha loãng hoàn toàn",
      change5m: "5P",
      change1h: "1H",
      change6h: "6H",
      change24h: "24H",
      change24hFull: "TĐ 24H",
      vol24h: "Lượng GD 24H",
      vol24hTip: "Lượng giao dịch 24 giờ",
      buy: "MUA",
      sell: "BÁN",
      net: "RÒNG",
      txns24h: "SỐ GD 24H",
      txns24hTip: "Số giao dịch 24 giờ",
      traders24h: "SỐ NGƯỜI GIAO DỊCH 24H",
      top10Holders: "TOP 10 NGƯỜI NẮM GIỮ",
      holders: "NGƯỜI NẮM GIỮ",
      circSupply: "CUNG LƯU HÀNH",
      totalSupply: "TỔNG CUNG",
      markets: "THỊ TRƯỜNG",
    },
    recentTransactions: {
      transactions: "Giao dịch",
      bubblemaps: "Bubblemaps",
      time: "Thời gian",
      type: "Loại",
      price: "Giá",
      priceUsd: "Giá",
      amount: "Số lượng",
      value: "Giá trị",
      from: "Từ",
      tx: "TX",
      buy: "MUA",
      sell: "BÁN",
      loading: "Đang tải...",
      empty: "Không có giao dịch gần đây",
      noAddress: "Không có địa chỉ token",
    },
    topHolders: {
      rank: "Thứ hạng",
      address: "Địa chỉ",
      percent: "Phần trăm",
      noData: "Không tìm thấy dữ liệu người nắm giữ.",
    },
    historicalData: {
      title: "Lịch sử giá {{name}}",
      date: "Ngày",
      marketCap: "Vốn hóa",
      volume: "Khối lượng",
      close: "Giá đóng cửa",
      showMore: "Xem thêm",
      error:
        "Không thể tải dữ liệu lịch sử. Token này có thể chưa được niêm yết trên CoinGecko.",
    },
    insightTabs: {
      about: "Thống kê",
      holders: "Người nắm giữ",
      noDescription: "Không có mô tả.",
      distributionTitle: "Phân bổ người nắm giữ",
      distributionDescription:
        "Phân bổ quyền sở hữu token {{symbol}} theo nhóm người nắm giữ hàng đầu.",
      top10: "Top 10",
      rank1120: "11-20",
      rank2140: "21-40",
      rank1130: "11-30",
      rank3150: "31-50",
      others: "Khác",
      volumeQ:
        "Khối lượng giao dịch hàng ngày của {{name}} ({{symbol}}) là bao nhiêu?",
      volumeA:
        "Khối lượng giao dịch 24h của {{name}} ({{symbol}}) là {{volume}}, biến động {{change}} so với ngày hôm trước.",
      athAtlQ:
        "Giá cao nhất và thấp nhất mọi thời đại của {{name}} ({{symbol}}) là bao nhiêu?",
      athAtlA:
        "{{name}} ({{symbol}}) đạt đỉnh cao mọi thời đại là {{ath}} và đáy thấp nhất là {{atl}}. Hiện đang giao dịch {{athPct}} so với đỉnh và {{atlPct}} trên mức thấp nhất đã ghi nhận.",
      marketCapQ: "Vốn hóa thị trường của {{name}} ({{symbol}}) là bao nhiêu?",
      marketCapA:
        "Vốn hóa thị trường của {{name}} ({{symbol}}) là {{marketCap}}, xếp hạng #{{rank}} theo vốn hóa hôm nay. Vốn hóa được tính bằng giá token nhân với nguồn cung lưu hành — {{supply}} token đang lưu thông trên thị trường.",
      fdvQ: "Định giá pha loãng hoàn toàn của {{name}} ({{symbol}}) là bao nhiêu?",
      fdvA: "Định giá pha loãng hoàn toàn (FDV) của {{name}} ({{symbol}}) là {{fdv}}. Đây là biểu diễn thống kê của vốn hóa tối đa, giả định toàn bộ {{maxSupply}} token đang lưu thông hôm nay. Tùy theo lịch phát hành, FDV có thể mất nhiều năm để được thực hiện đầy đủ.",
      supplyBillion: "{{count}} tỷ {{symbol}}",
      supplyMillion: "{{count}} triệu {{symbol}}",
      supplyThousand: "{{count}} nghìn {{symbol}}",
    },
    globalPrices: {
      title: "Giá {{name}} toàn cầu",
      description: "Giá {{name}} theo các đơn vị tiền tệ lớn trên thế giới.",
      showMore: "Xem thêm",
    },
  },
  tooltips: {
    marketCap:
      "Giá hiện tại x Số lượng lưu hành. Đây là tổng giá trị thị trường của nguồn cung lưu hành của một loại tiền điện tử. Nó tương tự như cách đo lường của thị trường chứng khoán khi nhân giá mỗi cổ phiếu với số cổ phiếu có sẵn trên thị trường (không bao gồm cổ phiếu do người trong cuộc, chính phủ nắm giữ và khóa lại).",
    fullyDilutedValuation:
      "Vốn hóa thị trường của một loại tiền điện tử nếu tất cả các đồng tiền có thể được lưu hành đều có mặt trên thị trường. Nó được tính bằng cách nhân giá hiện tại với tổng cung tối đa của loại tiền điện tử đó.",
    tradingVolume24h:
      "Tổng khối lượng giao dịch của token trong 24 giờ qua trên tất cả các sàn giao dịch. Đây là một thước đo về mức độ hoạt động của token và có thể cho thấy tính thanh khoản và sự quan tâm của thị trường đối với token đó.",
    circulatingSupply:
      "Tổng số đồng tiền hoặc token hiện có và đang lưu hành trên thị trường. Nó được sử dụng để tính toán vốn hóa thị trường của một loại tiền điện tử.",
    totalSupply:
      "Tổng số đồng tiền hoặc token tồn tại cho một loại tiền điện tử, bao gồm cả những đồng chưa lưu hành. Nó được sử dụng để tính toán vốn hóa thị trường tối đa tiềm năng của một loại tiền điện tử.",
    maxSupply:
      "Số lượng tối đa đồng tiền hoặc token sẽ tồn tại cho một loại tiền điện tử. Nó được sử dụng để tính toán giá trị định giá đầy đủ của một loại tiền điện tử.",
  },
  profileSettings: {
    identity: "Thông tin cá nhân",
    displayName: "Tên hiển thị",
    email: "Email",
    saveIdentity: "Lưu thông tin",
    savingIdentity: "Đang lưu thông tin",
    identityUpdateFailed: "Cập nhật thông tin thất bại",
    identityUpdated: "Thông tin đã được cập nhật",
    loginMethods: "Phương thức đăng nhập",
    loginMethodPasswordEmail: "Mật khẩu / Email",
    loginMethodPasswordNotSet: "Chưa được đặt",
    loginMethodGoogleOAuth: "Google Mail OAuth",
    loginMethodSolanaWallet: "Ví Solana",
    statusConnected: "Đã kết nối",
    statusNotConnected: "Chưa kết nối",
    changePassword: "Đổi mật khẩu",
    addPassword: "Thêm mật khẩu",
    currentPassword: "Mật khẩu hiện tại",
    newPassword: "Mật khẩu mới",
    confirmPassword: "Xác nhận mật khẩu",
    passwordMatchError: "Mật khẩu mới và xác nhận không khớp",
    passwordValidationEmailRequired:
      "Email là bắt buộc để thiết lập đăng nhập mật khẩu",
    passwordValidationEmailInvalid: "Vui lòng nhập địa chỉ email hợp lệ",
    passwordValidationCurrentPasswordRequired:
      "Mật khẩu hiện tại là bắt buộc để đổi mật khẩu",
    passwordValidationNewPasswordRequired: "Mật khẩu mới là bắt buộc",
    passwordValidationMinLength: "Mật khẩu phải có ít nhất 8 ký tự",
    passwordValidationUppercase:
      "Mật khẩu phải chứa ít nhất một chữ cái viết hoa",
    passwordValidationLowercase:
      "Mật khẩu phải chứa ít nhất một chữ cái viết thường",
    passwordValidationNumber: "Mật khẩu phải chứa ít nhất một chữ số",
    passwordUpdateFailed: "Cập nhật mật khẩu thất bại",
    passwordChanged: "Mật khẩu đã được thay đổi",
    passwordAdded: "Mật khẩu đã được thêm",
    updatingPassword: "Đang cập nhật mật khẩu",
    savePassword: "Lưu mật khẩu",
    dangerZone: "Vùng nguy hiểm",
    dangerZoneDescription:
      "Xóa tài khoản sẽ loại bỏ hồ sơ và tất cả dữ liệu xác thực/ví được liên kết.",
    deleteAccount: "Xóa tài khoản",
    deleteAccountWarning:
      "Hành động này không thể hoàn tác. Vui lòng nhập DELETE MY ACCOUNT để xác nhận.",
    deleteAccountConfirmationText: "Văn bản xác nhận",
    deleteAccountConfirmButton: "Xác nhận xóa",
    accountDeleteConfirmError: "Văn bản xác nhận không khớp",
    accountDeleteFailed: "Xóa tài khoản thất bại",
  },
  profileTabs: {
    activity: {
      title: "Hoạt động",
      unavailableTitle: "Hoạt động không có sẵn",
      unavailableDescription: "Không thể tải dữ liệu hoạt động ngay bây giờ.",
      swapsTableTitle: "Giao dịch hoán đổi",
      transfersTableTitle: "Chuyển khoản",
      tableHeaders: {
        swaps: {
          wallet: "Ví",
          time: "Thời gian",
          pair: "Cặp",
          exchange: "Sàn giao dịch",
          totalValue: "Giá trị tổng",
        },
      },
      unknownExchange: "Không xác định",
    },
    alerts: {
      title: "Cảnh báo",
      unavailableTitle: "Cảnh báo không có sẵn",
      unavailableDescription:
        "Không có quy tắc cảnh báo hoặc thông báo nào có sẵn ngay bây giờ.",
      tableTitle: "Danh sách cảnh báo",
      tableHeaders: {
        token: "Token",
        type: "Loại",
        condition: "Điều kiện",
        status: "Trạng thái",
        updated: "Cập nhật",
        actions: "Hành động",
      },
      createAlertTitle: "Tạo cảnh báo",
      editAlertTitle: "Chỉnh sửa cảnh báo {{token}}",
      createButton: "Tạo cảnh báo",
      editButton: "Chỉnh sửa",
      deleteButton: "Xóa",
    },
    dashboard: {
      title: "Bảng điều khiển",
      unavailableTitle: "Bảng điều khiển không có sẵn",
      unavailableDescription:
        "Không có số liệu bảng điều khiển nào có sẵn cho tài khoản này.",
      kpiStripTitle: "Dải KPI",
      concentrationTableTitle: "Tập trung ví",
      concentrationHeaders: {
        wallet: "Ví",
        value: "Giá trị",
        share: "Chia sẻ",
      },
      riskPanelTitle: "Bảng rủi ro",
      anomaliesTitle: "Các bất thường gần đây",
    },
    portfolio: {
      title: "Danh mục đầu tư",
      unavailableTitle: "Không có ví được liên kết",
      unavailableDescription:
        "Liên kết ít nhất một ví để xem danh mục đầu tư và biểu đồ.",
      overviewCardTitle: "Tổng quan",
      accountTierLabel: "Cấp tài khoản",
      linkWalletButton: "Liên kết ví",
      linkedWalletsLabel: "Ví được liên kết",
      linkedWalletsList: "Danh sách ví liên kết",
      wallet: "Ví",
      address: "Địa chỉ",
      netWorth: "Giá trị ròng",
      auth: "Xác thực",
      actions: "Hành động",
      authWallet: "Ví xác thực",
      authWalletLabel: "Ví xác thực",
      linkedWalletLabel: "Ví được liên kết",
      compare: "So sánh",
      authWalletCannotBeUnlinked: "Không thể hủy liên kết ví xác thực",
      unlinkWallet: "Hủy liên kết ví",
    },
    wallet: {
      title: "Ví",
      unavailableTitle: "Dữ liệu ví không có sẵn",
      unavailableDescription: "Không thể tải dữ liệu ví ngay bây giờ.",
      noLinkedWalletsTitle: "Không có ví được liên kết",
      noLinkedWalletsDescription:
        "Liên kết ít nhất một ví để xem danh mục đầu tư và biểu đồ.",
      portfolioTableTitle: "Bảng danh mục đầu tư",
      balanceChartTitle: "Cân bằng",
      drawdownChartTitle: "Rút ngắn",
    },
    watchlist: {
      title: "Danh sách theo dõi",
      walletSubtab: "Theo dõi ví",
      tokenSubtab: "Theo dõi token",
      walletTableTitle: "Ví đang theo dõi",
      tokenTableTitle: "Token đang theo dõi",
      walletAddress: "Địa chỉ ví",
      walletIdentity: "Danh tính",
      emptyWalletTitle: "Chưa có ví trong danh sách theo dõi",
      emptyWalletDescription:
        "Hãy thêm ví vào danh sách theo dõi để xem tại đây.",
      emptyTokenTitle: "Chưa có token trong danh sách theo dõi",
      emptyTokenDescription:
        "Hãy thêm token vào danh sách theo dõi để theo dõi biến động thị trường.",
    },
    unavailableState: {
      defaultTitle: "Dữ liệu không có sẵn",
      defaultDescription: "Không có dữ liệu hồ sơ nào có sẵn ngay bây giờ.",
    },
  },
});
