import { define } from "./en";
import type { NumberFormatInfo } from "./util/util-format";

export const viNumFmtInfo: NumberFormatInfo = {
  thousandSeparator: ".",
  decimalSeparator: ",",
  currencySymbol: "VNĐ",
  currencyPositivePattern: "n$",
  currencyNegativePattern: "-n$",
  percentSymbol: "%",
  percentPositivePattern: "n%",
  percentNegativePattern: "-n%",
  NaNSymbol: "NaN",
  positiveInfititySymbol: "∞",
  negativeInfititySymbol: "-∞",
  numberNegativePattern: "-n",
};

export const vi = define({
  // Common
  common: {
    cancel: "Hủy",
    confirm: "Xác nhận",
    submit: "Gửi",
    loading: "Đang tải...",
    error: "Lỗi",
    success: "Thành công",
    or: "hoặc",
    and: "và",
  },
  // Authentication
  auth: {
    or: "Hoặc tiếp tục với",
    signIn: "Đăng nhập",
    signUp: "Đăng ký",
    signOut: "Đăng xuất",
    email: "Email",
    username: "Tên người dùng",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    retypePassword: "Nhập lại mật khẩu",
    forgotPassword: "Quên mật khẩu?",
    alreadyHaveAccount: "Đã có tài khoản?",
    wantAccount: "Muốn có tài khoản?",
    createAccount: "Tạo tài khoản",
    continueWithGoogle: "Tiếp tục với Google",
    signUpWithGoogle: "Đăng ký với Google",
    continueWithWallet: "Tiếp tục với ví đã liên kết",
    signUpWithWallet: "Đăng ký với ví hiện có",
    termsAndPrivacy:
      "Bằng việc đăng ký, bạn đồng ý với {{terms}} và {{privacy}} của chúng tôi",
    termsPrefix: "Bằng việc đăng ký, bạn đồng ý với",
    termsOfService: "Điều khoản dịch vụ",
    privacyPolicy: "Chính sách bảo mật",
    terms: "Điều khoản dịch vụ",
    privacy: "Chính sách bảo mật",
    googleAuthFailed: "Xác thực Google thất bại. Vui lòng thử lại.",
    googleAuthCancelled: "Xác thực Google đã bị hủy.",
  },
  // Wallet
  wallet: {
    connectWallet: "Kết nối ví",
    selectWallet: "Chọn một ví",
    detected: "Đã phát hiện",
    notDetected: "Không phát hiện ví",
    installWallet: "Vui lòng cài đặt tiện ích ví Solana",
    blockchain: "Blockchain",
    connecting: "Đang kết nối...",
    connectionFailed: "Kết nối thất bại",
    retry: "Thử lại",
    popularWallets: "Ví Solana phổ biến",
    connectToSignIn: "Kết nối ví để đăng nhập",
    connectToSignUp: "Kết nối ví để đăng ký",
    web3Auth: "Xác thực Web3",
    selectBlockchain: "Chọn Blockchain",
    solana: "Solana",
    ethereum: "Ethereum",
    bitcoin: "Bitcoin",
    detectingWallets: "Đang phát hiện ví...",
    scanningWallets: "Đang quét ví {{blockchain}} đã cài đặt...",
    detectedWallets: "Ví đã phát hiện",
    otherWallets: "Ví khác",
    noWalletsDetected: "Không phát hiện ví",
    noWalletsFound: "Không tìm thấy ví {{blockchain}}",
    installWalletPrompt:
      "Vui lòng cài đặt tiện ích ví để tiếp tục. Nhấp vào ví bên dưới để truy cập trang cài đặt.",
    install: "Cài đặt →",
    termsAgreement:
      "Bằng việc kết nối ví, bạn đồng ý với Điều khoản dịch vụ và Chính sách bảo mật của chúng tôi.",
    detectionFailed: "Không thể phát hiện ví. Vui lòng thử lại.",
  },
  // Navigation
  nav: {
    market: "Thị trường",
    alert: "Cảnh báo",
    dashboard: "Bảng điều khiển",
    profile: "Hồ sơ",
    settings: "Cài đặt",
    language: "Ngôn ngữ",
    theme: "Giao diện",
  },
  // Validation errors
  validation: {
    required: "Trường này là bắt buộc",
    identifierRequired: "Tên người dùng hoặc email là bắt buộc",
    identifierInvalid:
      "Vui lòng nhập email hoặc tên người dùng hợp lệ (tối thiểu 3 ký tự)",
    emailRequired: "Email là bắt buộc",
    invalidEmail: "Vui lòng nhập địa chỉ email hợp lệ",
    usernameRequired: "Tên người dùng là bắt buộc",
    usernameTooShort: "Tên người dùng phải có ít nhất 3 ký tự",
    usernameTooLong: "Tên người dùng không được quá 20 ký tự",
    usernameInvalidChars:
      "Tên người dùng chỉ được chứa chữ cái, số và dấu gạch dưới",
    passwordRequired: "Mật khẩu là bắt buộc",
    passwordTooShort: "Mật khẩu phải có ít nhất {{min}} ký tự",
    passwordComplexity:
      "Mật khẩu phải chứa ít nhất một chữ hoa, một chữ thường và một số",
    confirmPasswordRequired: "Vui lòng xác nhận mật khẩu",
    passwordsDoNotMatch: "Mật khẩu không khớp",
    invalidCredentials: "Tên người dùng hoặc mật khẩu không hợp lệ",
    accountExists: "Tài khoản với email này đã tồn tại",
    networkError: "Lỗi mạng. Vui lòng thử lại.",
    registrationFailed: "Đăng ký thất bại. Vui lòng thử lại.",
  },
  // Showcase page
  showcase: {
    title: "Bộ sưu tập component Yoca",
    subtitle: "Xác thực & Điều hướng UI",
    signInSection: "Component đăng nhập",
    signUpSection: "Component đăng ký",
    walletSection: "Kết nối ví",
    googleAuthSection: "Xác thực Google",
    navigationSection: "Thanh điều hướng",
    placeholderContent: "Đây là nội dung mẫu để minh họa.",
  },
  // Charts
  charts: {
    // Common
    loading: "Đang tải dữ liệu biểu đồ...",
    refreshing: "Đang làm mới...",
    retry: "Thử lại",
    export: "Xuất",
    fullscreen: "Toàn màn hình",
    miniPlayer: "Trình phát nhỏ",
    exitFullscreen: "Thoát toàn màn hình",

    // Viewing modes
    enterFullscreenMode: "Vào chế độ toàn màn hình",
    openMiniPlayer: "Mở trình phát nhỏ",
    chartViewingModes: "Chế độ xem biểu đồ",
    fullscreenView: "Chế độ toàn màn hình",
    exitFullscreenEsc: "Thoát toàn màn hình (ESC)",
    closeMiniPlayer: "Đóng trình phát nhỏ",
    closeMiniPlayerEsc: "Đóng trình phát nhỏ (ESC)",
    dragToMove: "Kéo để di chuyển",
    maximize: "Phóng to",
    minimize: "Thu nhỏ",

    // Timezone
    selectTimezone: "Chọn múi giờ",
    timezone: "Múi giờ",
    timezoneOptions: "Tùy chọn múi giờ",
    searchTimezones: "Tìm kiếm múi giờ...",
    noTimezonesFound: "Không tìm thấy múi giờ",
    localTime: "Giờ địa phương",
    utc: "UTC",

    // Loading states
    loadingChartData: "Đang tải dữ liệu biểu đồ {{title}}",
    refreshingChartData: "Đang làm mới dữ liệu biểu đồ {{title}}",
    chartLoadedSuccessfully: "Biểu đồ {{title}} đã tải thành công",
    errorLoadingChart: "Lỗi khi tải biểu đồ {{title}}",
    noDataForChart: "Không có dữ liệu cho biểu đồ {{title}}",

    // Empty state
    noDataTitle: "Không có dữ liệu",
    noDataMessage: "Không có dữ liệu để hiển thị cho bộ lọc đã chọn.",
    resetFilters: "Đặt lại bộ lọc",
    adjustFilters: "Thử điều chỉnh bộ lọc hoặc khoảng thời gian",

    // Error state
    errorTitle: "Không thể tải biểu đồ",
    errorMessage: "Đã xảy ra lỗi khi tải dữ liệu biểu đồ.",
    technicalDetails: "Chi tiết kỹ thuật",
    networkError: "Lỗi mạng. Vui lòng kiểm tra kết nối.",
    serverError: "Lỗi máy chủ. Vui lòng thử lại sau.",

    // Export
    exportChart: "Xuất biểu đồ",
    exportFormatOptions: "Tùy chọn định dạng xuất",
    exportPNG: "Xuất dưới dạng PNG",
    exportSVG: "Xuất dưới dạng SVG",
    exportCSV: "Xuất dưới dạng CSV",
    pngFormat: "PNG",
    svgFormat: "SVG",
    csvFormat: "CSV",
    retinaBadge: "Ảnh",
    vectorBadge: "Vector",
    dataBadge: "Dữ liệu",
    exportSuccess: "Xuất biểu đồ thành công",
    exportFailed: "Xuất thất bại. Vui lòng thử lại.",

    // Filters
    timePeriod: "Khoảng thời gian",
    last7Days: "7 ngày qua",
    last30Days: "30 ngày qua",
    last60Days: "60 ngày qua",
    last90Days: "90 ngày qua",
    lastYear: "Năm qua",
    allTime: "Toàn bộ thời gian",
    customRange: "Tùy chỉnh",
    tokens: "Token",
    allTokens: "Tất cả Token",
    transactionType: "Loại giao dịch",
    allTypes: "Tất cả loại",
    trades: "Giao dịch",
    transfers: "Chuyển khoản",
    deposits: "Nạp tiền",
    withdrawals: "Rút tiền",
    wallets: "Ví",

    // Chart titles
    balanceTrend: "Xu hướng số dư",
    assetDistribution: "Phân bổ tài sản",
    profitLoss: "Lãi & Lỗ",
    exchangeComparison: "So sánh sàn giao dịch",
    counterpartyActivity: "Hoạt động đối tác",
    volumeBenchmark: "Đánh giá khối lượng",
    transactionDistribution: "Phân bổ giao dịch",
    holdingDurations: "Thời gian nắm giữ",

    // Chart specific
    balanceChart: {
      title: "Xu hướng số dư",
      totalBalance: "Tổng số dư",
      change: "Thay đổi",
      date: "Ngày",
      balance: "Số dư",
    },
    assetDistributionChart: {
      title: "Phân bổ tài sản",
      totalValue: "Tổng giá trị",
      asset: "Tài sản",
      value: "Giá trị",
      percentage: "Phần trăm",
    },
    pnlChart: {
      title: "Lãi & Lỗ",
      dailyPnL: "Lãi/Lỗ hàng ngày",
      cumulativePnL: "Lãi/Lỗ tích lũy",
      profit: "Lãi",
      loss: "Lỗ",
      date: "Ngày",
      totalProfit: "Tổng lãi",
      totalLoss: "Tổng lỗ",
      netPnL: "Lãi/Lỗ ròng",
      aggregation: "Tổng hợp",
      daily: "Hàng ngày",
      weekly: "Hàng tuần",
      monthly: "Hàng tháng",
    },
    exchangeComparisonChart: {
      title: "So sánh hoạt động sàn giao dịch",
      exchange: "Sàn giao dịch",
      deposits: "Nạp tiền",
      withdrawals: "Rút tiền",
      count: "Số giao dịch",
      volume: "Khối lượng (USD)",
      metric: "Chỉ số",
      transactionCount: "Số giao dịch",
      volumeUSD: "Khối lượng (USD)",
    },
    counterpartyActivityChart: {
      title: "Phân tích hoạt động đối tác",
      counterparty: "Đối tác",
      transactionCount: "Số giao dịch",
      totalVolume: "Tổng khối lượng",
      limit: "Hiển thị top",
      top10: "Top 10",
      top20: "Top 20",
      top50: "Top 50",
    },
    volumeBenchmarkChart: {
      title: "So sánh khối lượng giao dịch",
      volume: "Khối lượng",
      date: "Ngày",
      wallet: "Ví",
      chartType: "Loại biểu đồ",
      line: "Đường",
      bar: "Cột",
      showLabels: "Hiển thị nhãn",
    },
    transactionDistributionChart: {
      title: "Phân tích hoạt động giao dịch",
      transactionCounts: "Số lượng giao dịch",
      uniqueTokens: "Số loại Token được giao dịch",
      date: "Ngày",
      count: "Số lượng",
      tokens: "Token",
      chartMode: "Chế độ biểu đồ",
      stacked: "Xếp chồng",
      grouped: "Nhóm",
    },
    holdingDurationsChart: {
      title: "Thời gian nắm giữ token",
      token: "Token",
      duration: "Thời gian",
      days: "Ngày",
      weeks: "Tuần",
      months: "Tháng",
      timeUnit: "Đơn vị thời gian",
      topN: "Hiển thị top",
      wallet: "Ví",
    },
  },
});
