import type { ProfilePageData } from "@/types/profile";

const TODAY = "2026-04-07";

export const profileMockApiPayload: ProfilePageData = {
    overview: {
        avatarUrl:
            "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=60",
        displayName: "Alex Solana",
        accountTier: "premium",
        period: "30D",
        totalNetWorthUsd: 145250.77,
        tradeOrTxCount: 1842,
        pnlUsd: 16420.15,
        pnlPct: 12.74,
        linkedWalletCount: 4,
    },
    dashboard: {
        kpis: [
            { id: "net-worth-trend", label: "Net worth trend", value: "+8.2%", tone: "positive" },
            { id: "realized", label: "Realized PnL", value: "$9,122", tone: "positive" },
            { id: "unrealized", label: "Unrealized PnL", value: "$7,298", tone: "positive" },
            { id: "win-rate", label: "Win rate", value: "64%", tone: "neutral" },
            { id: "active-alerts", label: "Active alerts", value: "11", tone: "neutral" },
        ],
        concentration: [
            { label: "Main wallet", valueUsd: 64800, pct: 44.6 },
            { label: "Trading bot", valueUsd: 37500, pct: 25.8 },
            { label: "Vault", valueUsd: 24100, pct: 16.6 },
            { label: "Cold wallet", valueUsd: 18850, pct: 13.0 },
        ],
        risk: [
            { id: "max-drawdown", label: "Max drawdown (30d)", value: "-11.4%" },
            { id: "volatility", label: "Volatility proxy", value: "Medium" },
        ],
        anomalies: [
            {
                id: "an-1",
                title: "Large transfer spike",
                description: "Transfer volume jumped 4.2x versus previous 7-day average.",
                timestamp: `${TODAY}T08:20:00Z`,
            },
            {
                id: "an-2",
                title: "Trade frequency drift",
                description: "Trade frequency dropped 26% in the last 48 hours.",
                timestamp: `${TODAY}T04:10:00Z`,
            },
        ],
    },
    alerts: {
        leftNavItems: ["list", "editor"],
        selectedNav: "list",
        alerts: [
            {
                id: "alert-1",
                tokenSymbol: "SOL",
                alertType: "price",
                conditionText: "Price > 210",
                status: "active",
                updatedAt: `${TODAY}T10:21:00Z`,
            },
            {
                id: "alert-2",
                tokenSymbol: "JUP",
                alertType: "volume",
                conditionText: "Volume spike > 2.5x",
                status: "paused",
                updatedAt: `${TODAY}T09:03:00Z`,
            },
            {
                id: "alert-3",
                tokenSymbol: "BONK",
                alertType: "drawdown",
                conditionText: "Drawdown > 8%",
                status: "triggered",
                updatedAt: `${TODAY}T06:34:00Z`,
            },
        ],
        notifications: [
            {
                id: "note-1",
                timestamp: `${TODAY}T10:25:00Z`,
                message: "SOL breached your $210 target.",
                severity: "warning",
            },
            {
                id: "note-2",
                timestamp: `${TODAY}T09:55:00Z`,
                message: "Portfolio drawdown crossed 8.0%.",
                severity: "critical",
            },
            {
                id: "note-3",
                timestamp: `${TODAY}T08:44:00Z`,
                message: "New high-volume signal detected for JUP.",
                severity: "info",
            },
        ],
    },
    wallets: {
        leftNavItems: [
            "portfolio-table",
            "linked-wallets",
            "balance-chart",
            "drawdown-chart",
        ],
        selectedNav: "portfolio-table",
        portfolioRows: [
            {
                walletId: "w1",
                walletLabel: "Main wallet",
                netWorthUsd: 64800,
                pnlUsd: 8200,
                pnlPct: 14.49,
                tradeCount: 501,
            },
            {
                walletId: "w2",
                walletLabel: "Trading bot",
                netWorthUsd: 37500,
                pnlUsd: 4210,
                pnlPct: 9.81,
                tradeCount: 811,
            },
            {
                walletId: "w3",
                walletLabel: "Vault",
                netWorthUsd: 24100,
                pnlUsd: 2690,
                pnlPct: 12.56,
                tradeCount: 303,
            },
            {
                walletId: "w4",
                walletLabel: "Cold wallet",
                netWorthUsd: 18850,
                pnlUsd: 1320,
                pnlPct: 7.53,
                tradeCount: 227,
            },
        ],
        linkedWalletRows: [
            {
                walletId: "w1",
                walletAddress: "5iM4Yj8RQ6m29zNShxCe4dfQ1Qx7sQeX",
                walletLabel: "Main wallet",
                netWorthUsd: 64800,
                lastActiveAt: `${TODAY}T07:54:00Z`,
                status: "connected",
            },
            {
                walletId: "w2",
                walletAddress: "8MxaQf7BdKe2j41nPb4vVtF2xMUnnD22",
                walletLabel: "Trading bot",
                netWorthUsd: 37500,
                lastActiveAt: `${TODAY}T07:20:00Z`,
                status: "connected",
            },
            {
                walletId: "w3",
                walletAddress: "92csH3fQ6dA1uZzN4Yx3rPqB9RjBZZw9",
                walletLabel: "Vault",
                netWorthUsd: 24100,
                lastActiveAt: `${TODAY}T05:02:00Z`,
                status: "inactive",
            },
        ],
        selectedComparisonWalletIds: ["w1", "w2"],
        walletDetailRouteTemplate: "/wallets/:walletId",
        comparisonTargetRoute: "/comparison/wallets",
    },
    activity: {
        leftNavItems: [
            "swaps-table",
            "transfers-table",
            "wallet-overview-cards",
            "trade-frequency-heatmap",
        ],
        selectedNav: "swaps-table",
        swapTransferRows: [
            {
                id: "act-1",
                walletId: "w1",
                walletLabel: "Main wallet",
                type: "swap",
                pairOrToken: "SOL/USDC",
                amountUsd: 1840,
                timestamp: `${TODAY}T09:41:00Z`,
                side: "buy",
            },
            {
                id: "act-2",
                walletId: "w2",
                walletLabel: "Trading bot",
                type: "swap",
                pairOrToken: "JUP/USDC",
                amountUsd: 520,
                timestamp: `${TODAY}T08:11:00Z`,
                side: "sell",
            },
            {
                id: "act-3",
                walletId: "w1",
                walletLabel: "Main wallet",
                type: "transfer",
                pairOrToken: "USDC",
                amountUsd: 2400,
                timestamp: `${TODAY}T07:30:00Z`,
                side: "out",
            },
        ],
        walletCards: [
            {
                walletId: "w1",
                walletLabel: "Main wallet",
                walletAddress: "5iM4Yj8RQ6m29zNShxCe4dfQ1Qx7sQeX",
                totalAssetValueUsd: 64800,
                unrealizedPnlInPeriodUsd: 1220,
                tradingVolumeUsd: 219400,
                buyTradingVolumeUsd: 124300,
                sellTradingVolumeUsd: 95100,
                buyTransactionCount: 282,
                sellTransactionCount: 219,
                tokenAmountTraded: 3740,
                tokenAmountHolding: 89,
                totalPnlUsd: 8200,
                realizedPnlUsd: 6980,
                unrealizedPnlUsd: 1220,
            },
            {
                walletId: "w2",
                walletLabel: "Trading bot",
                walletAddress: "8MxaQf7BdKe2j41nPb4vVtF2xMUnnD22",
                totalAssetValueUsd: 37500,
                unrealizedPnlInPeriodUsd: 610,
                tradingVolumeUsd: 304900,
                buyTradingVolumeUsd: 168400,
                sellTradingVolumeUsd: 136500,
                buyTransactionCount: 441,
                sellTransactionCount: 370,
                tokenAmountTraded: 6120,
                tokenAmountHolding: 46,
                totalPnlUsd: 4210,
                realizedPnlUsd: 3600,
                unrealizedPnlUsd: 610,
            },
            {
                walletId: "w3",
                walletLabel: "Vault",
                walletAddress: "92csH3fQ6dA1uZzN4Yx3rPqB9RjBZZw9",
                totalAssetValueUsd: 24100,
                unrealizedPnlInPeriodUsd: -190,
                tradingVolumeUsd: 138700,
                buyTradingVolumeUsd: 69700,
                sellTradingVolumeUsd: 69000,
                buyTransactionCount: 149,
                sellTransactionCount: 154,
                tokenAmountTraded: 2410,
                tokenAmountHolding: 132,
                totalPnlUsd: 2690,
                realizedPnlUsd: 2880,
                unrealizedPnlUsd: -190,
            },
        ],
        heatmap: {
            maxCount: 12,
            cells: [
                { date: "2026-03-31", count: 3 },
                { date: "2026-04-01", count: 5 },
                { date: "2026-04-02", count: 8 },
                { date: "2026-04-03", count: 2 },
                { date: "2026-04-04", count: 10 },
                { date: "2026-04-05", count: 7 },
                { date: "2026-04-06", count: 12 },
                { date: "2026-04-07", count: 6 },
            ],
        },
    },
};
